### ISSUE TITLE
circular dependency on python3-beautifulsoup?

### ISSUE THREAD

**Issue by vermaete** [priv-kweihmann/meta-sca#10187]
Hi Konrad,

This error is thrown when adding `INHERIT += "sca"` and buiding `core-image-base` of `raspberrypi4-64`.

```
ERROR: Task virtual:native:/home/vermaete/projects/mykas/layers/meta-openembedded/meta-python/recipes-devtools/python/python3-beautifulsoup4_4.11.1.bb:do_populate_sysroot has circular dependency on virtual:native:/home/vermaete/projects/mykas/layers/meta-openembedded/meta-python/recipes-devtools/python/python3-soupsieve_2.3.1.bb:do_populate_sysroot
ERROR: Command execution failed: 1
```

meta-sca at master (cbb0851e30569bce0017aedcb058bf4c4abeec89)
poky, and all others also at master:
poky: b9223d27bdebd1356b3ece4c8735f561c947d47d
meta-openembedded: 2eb39477a784673baefa59640909b827ebb689b2

kas: https://github.com/vermaete/mykas/blob/main/kas-sca.yml

Are these recipes to be merged on day?
```
./meta-sca/recipes-python/python-beautifulsoup4-native/python3-beautifulsoup4-native_4.11.1.bb
./meta-openembedded/meta-python/recipes-devtools/python/python3-beautifulsoup4_4.11.1.bb
```

If you could put me on the correct path I could do a fair attempt to solve it.

Br

**Comment by priv-kweihmann** [comment]
That looks odd, if any other layer provides this recipe it shouldn't be picked at all.
Give me a day or two and let me try to reproduce this on my setup, but it's definitely a bug and should happen like this

**Comment by priv-kweihmann** [comment]
As a temporary workaround you can always BBMASK the two recipes

**Comment by vermaete** [comment]
Hi,

BBMASKing doesn't help: https://github.com/vermaete/mykas/commit/ce12666e550127be84a16ae409b913d60ae7ab6c

Thanks for the support.  If you want I can check something else.

**Comment by vermaete** [comment]
With this, it seems to work.
one of them?  If it helps.

```
diff --git a/recipes-python/python-commoncode-native/python3-commoncode-native_30.0.0.bb b/recipes-python/python-commoncode-native/python3-commoncode-native_30.0.0.bb
index 230e26056..7bd1f358b 100644
--- a/recipes-python/python-commoncode-native/python3-commoncode-native_30.0.0.bb
+++ b/recipes-python/python-commoncode-native/python3-commoncode-native_30.0.0.bb
@@ -7,7 +7,6 @@ LIC_FILES_CHKSUM = "file://apache-2.0.LICENSE;md5=86d3f3a95c324c9479bd8986968f43
 
 DEPENDS += "\
             python3-attrs-native \
-            python3-beautifulsoup4-native \
             python3-click-native \
             python3-intbitset-native \
             python3-requests-native \
diff --git a/recipes-sca/python3-scancode-native/python3-scancode-native_30.1.0.bb b/recipes-sca/python3-scancode-native/python3-scancode-native_30.1.0.bb
index 6e813582d..e50eea41a 100755
--- a/recipes-sca/python3-scancode-native/python3-scancode-native_30.1.0.bb
+++ b/recipes-sca/python3-scancode-native/python3-scancode-native_30.1.0.bb
@@ -10,7 +10,6 @@ LIC_FILES_CHKSUM = "\
 
 DEPENDS += "\
             python3-attrs-native \
-            python3-beautifulsoup4-native \
             python3-bitarray-native \
             python3-booleanpy-native \
             python3-chardet-native \

```

**Comment by priv-kweihmann** [comment]
No your proposed patch would break scancode integration. The actual problem is within meta-python and the modules itself.
bs4 depends on soupsieve and soupsieve depends on bs4 - bitbake just can't resolve that for the native case where every RDEPENDS is turned into a DEPENDS.

You can try it by building python3-soupsieve-native without meta-sca in the bblayers.conf.

For the recipes provided in this layer it works, as I removed the DEPENDS of soupsieve.
If you still need to use meta-python then just add `RDEPENDS:${PN}:class-native:pn-python3-soupsieve-native = ""` to your local.conf, which should work around this issue.

Feel also free to report this to meta-python maintainers
