### ISSUE TITLE
SCA_ALLOW_LAYER/SCA_SPARE_LAYER/SCA_SPARE_DIRS doesn't work like expected

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#10249]
- with SCA_ALLOW_LAYER it should be assumed that sca modules are applicable to all modules of layers mentioned
- with SCA_SPARE_LAYER layers mentioned should be excluded from the checks
- with SCA_SPARE_DIRS single dirs can be ignored

currently this doesn't work

**Comment by priv-kweihmann** [comment]
@yangpeng1995 please check if it's now working according to your understanding

**Comment by yangpeng1995** [comment]
Hi priv-kweihmann,

Sorry for the late reply, it's now working with my understanding. 
But I had another problem running SCA, it's unable to find python_hatchling.bbclass.
I see from the history that you deleted it, but I didn't find it in the Poky upstream: https://git.yoctoproject.org/poky/tree/meta/classes

Where can this missing bbclass be inherit?

**Comment by priv-kweihmann** [comment]
Cool that it's working for you now.
The hatchling class was added in poky master around 3-4 weeks back, in before this was part of meta-python.
I suspect that you're not running on the latest greatest poky master, could you please check - and if you're bound to an older version you can add a copy to one of your own layers
