### ISSUE TITLE
filter out empty items in SCA_ALLOW_LAYER

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#10245]
Hi priv-kweihmann,
I recently found that the variable SCA_SPARE_LAYER is invalid when I enable SCA locally.
Then I debug found that it was caused by this submission.

I debug found that it was due to a problem with the judgment condition:
if _allow_list and x not in _allow_list:

The default variable of SCA_ALLOW_LAYER="".
So _allow_list = d.getVar("SCA_ALLOW_LAYER").split(" ")=[""].
But about judgment of "if _allow_list". In fact, "if [""]" value is true.
So this leads to always jumping out of the loop.

Can you help fix this bug?

_Originally posted by @yangpeng1995 in https://github.com/priv-kweihmann/meta-sca/issues/9490#issuecomment-1211593602_

**Comment by priv-kweihmann** [comment]
@yangpeng1995 will try to fix that today

**Comment by priv-kweihmann** [comment]
@yangpeng1995 that was easy, thank you so much for reporting, somehow that must slipped through

**Comment by yangpeng1995** [comment]
Thanks for the quick fix.

The SCA_SPARE_LAYER variable now works properly.

However, I would like to ask whether the implementation of SCA_ALLOW_LAYER really work? From the code, I can't see any effect of SCA_ALLOW_LAYER.

I think the original purpose of setting the variable is to only check the layers contained in the SCA_ALLOW_LAYER variable.

If I just want to check qt5-layer, then set the following variables:
INHERIT += "sca" in local.conf
SCA_ALLOW_LAYER = "qt5-layer"
SCA_SPARE_LAYER = "".
However, in addition to qt5-layer, it seems that other layers involved in compilation will also participate in check.
