### ISSUE TITLE
cppcheck options not making sense?

### ISSUE THREAD

**Issue by ravingraven** [priv-kweihmann/meta-sca#1035]
Hello,

I was looking at how cppcheck is invoked and noticed the following:

https://github.com/priv-kweihmann/meta-sca/blob/38edb5fa6784fa675254b434143452582dfb11d5/classes/sca-cppcheck.bbclass#L111-L112

First of all, how do those default make sense (--max-configs=1 effectively overwrites --force, right?). Secondly, would it not be better for the user to be able to modify all the defaults and add extra options on his/her own? Is there an obvious way to do this which I am missing?

Thanks!

**Comment by priv-kweihmann** [comment]
That could be true - it's been a long time since that code was written.
And no currently there is no defined way of specifying extra options to the tool - tbh I thought about that and haven't found the time to write a proper issue for this.
From my perspective this should (if done) applied to the other tools not only `cppcheck`.

**Comment by priv-kweihmann** [comment]
I will label this a bug here, as you're right the options don't make much sense - 
There are several options 
- leaving `--max-config=1` the default
- bundling `--max-config=1` with `SCA_CPPCHECK_RUNMODE == fast` and 
  `--force` with `SCA_CPPCHECK_RUNMODE == complete`

Or do you have any other ideas? - if so please let me know

**Comment by ravingraven** [comment]
I would go with the second option since it allows the user to make his/her own choice. I also think that `--max-configs=1` in general is far too restrictive, it means that only one configuration is checked (the default is 12).

Like I said, the ideal from a user POV is sensible defaults with the option to add/overwrite them. Do you accept pull requests? I am a novice Yocto user and far too unfamiliar with all other tools this layer supports, so I don't think I could create a patch that solves the problem for all tools but I might have some ideas about this one.

**Comment by priv-kweihmann** [comment]
`--max-config=1` does mean the currently effective configuration is check - no permutation is applied.
I've been working with this setting now for about 10 years - which is the best way to reduce execution time of the tool.
I'll add a parameter to tune this setting

**Comment by ravingraven** [comment]
> `--max-config=1` does mean the currently effective configuration is check - no permutation is applied.

With the current default configuration I get an error message about "Too many #ifdef configurations". This is why I assumed that it just refuses to to check if there is more than one configuration detected. Could be that I am using it wrong though. Anyway, thanks for fixing this.
