### ISSUE TITLE
Update cppcheck-native to 2.10

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#10904]

**Comment by shr-project** [comment]
Hi, the recipe says it's version 2.10.9, but it's actually just 2.10 (latest tag is 2.10.2). I've noticed this when upgrading cppcheck in https://github.com/shift-left-test/meta-shift/pull/11

**Comment by priv-kweihmann** [comment]
Huch, yeah - that must have been a typo - will fix that later on
