### ISSUE TITLE
Failed do_compile task of the sqlite3 (kirkstone branch)

### ISSUE THREAD

**Issue by Faduf** [priv-kweihmann/meta-sca#11077]
**Describe the bug**
The do_compile task of the sqlite3 package from poky is failing when I activate the gcc module (see console printouts below). If I use all modules from the example given in **meta-sca/tree/master/docs/conf/examples/img_complete.md** the do_compile task of sqlite3 fails. If I remove gcc from the list, the do_compile is ending without error. I tried to blocklist the gcc check of the sqlite3 package adding the parameter **SCA_BLOCKLIST_gcc = "sqlite3"** in the local.conf but it doesn't worked. 

**Used layer**
- meta-sca layer branch kirkstone - last commit hash : 37a122e97987c940560ac69d6b9755ee68ce0e4b
- poky branch kirkstone - last commit hash : c4e08719a782fd4119eaf643907b80cebf57f88f

**Used configuration**
- configuration from the example **meta-sca/tree/master/docs/conf/examples/img_complete.md**

**Additional**
yocto@nuc003:~/build-imx_imx-distro_security_sota_test_xwayland$ bitbake sqlite3 -c do_compile
NOTE: Started PRServer with DBfile: /home/yocto/build-imx_imx-distro_security_sota_test_xwayland/cache/prserv.sqlite3, Address: 127.0.0.1:42191, PID: 3069702
Loading cache: 100% |##########################################################################################################################################################| Time: 0:00:02
Loaded 5208 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-linux-gnueabi"
MACHINE              = "wandboard"
DISTRO               = "mydistro"
DISTRO_VERSION       = "2.7.0"
TUNE_FEATURES        = "arm vfp cortexa9 neon thumb callconvention-hard"
TARGET_FPU           = "hard"
meta-freescale       = "HEAD:1c7f17f6063d0b747d94a17059b176f3ebdb3e3e"
meta-oe              = "HEAD:a8055484f2829e8dfd03d5c8520b2c611aa7ebd2"
meta-poky            
meta                 = "HEAD:c4e08719a782fd4119eaf643907b80cebf57f88f"
meta-freescale-distro = "HEAD:d5bbb487b2816dfc74984a78b67f7361ce404253"
meta-security        = "HEAD:c79262a30bd385f5dbb009ef8704a1a01644528e"
meta-filesystems     = "HEAD:a8055484f2829e8dfd03d5c8520b2c611aa7ebd2"
meta-networking      = "HEAD:a8055484f2829e8dfd03d5c8520b2c611aa7ebd2"
meta-sca             = "kirkstone:37a122e97987c940560ac69d6b9755ee68ce0e4b"

Initialising tasks: 100% |#####################################################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 56 Local 56 Mirrors 0 Missed 0 Current 412 (100% match, 100% complete)
Removing 3 stale sstate objects for arch cortexa9t2hf-neon: 100% |#############################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
ERROR: sqlite3-3_3.38.5-r0 do_compile: oe_runmake failed
ERROR: sqlite3-3_3.38.5-r0 do_compile: ExecutionError('/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/temp/run.do_compile.3072367', 1, None, None)
ERROR: Logfile of failure stored in: /home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/temp/log.do_compile.3072367
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8
| arm-linux-gnueabi-gcc  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.38.5\" -DPACKAGE_STRING=\"sqlite\ 3.38.5\" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.38.5\" -D_FILE_OFFSET_BITS=64 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_POSIX_FALLOCATE=1 -I. -I../sqlite-autoconf-3380500    -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_GEOPOLY  -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBSTAT_VTAB  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwaylan
[log.do_compile.3072367.txt](https://github.com/priv-kweihmann/meta-sca/files/10971508/log.do_compile.3072367.txt)
d/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot-native=  -fanalyzer -DUSE_PREAD -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_BYTEORDER=1234 -c -o sqlite3-shell.o `test -f 'shell.c' || echo '../sqlite-autoconf-3380500/'`shell.c
| /bin/bash ./libtool  --tag=CC   --mode=compile arm-linux-gnueabi-gcc  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.38.5\" -DPACKAGE_STRING=\"sqlite\ 3.38.5\" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.38.5\" -D_FILE_OFFSET_BITS=64 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_POSIX_FALLOCATE=1 -I. -I../sqlite-autoconf-3380500    -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_GEOPOLY  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot-native=  -fanalyzer -DUSE_PREAD -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_BYTEORDER=1234 -c -o sqlite3.lo ../sqlite-autoconf-3380500/sqlite3.c
| libtool: compile:  arm-linux-gnueabi-gcc -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.38.5\" "-DPACKAGE_STRING=\"sqlite 3.38.5\"" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.38.5\" -D_FILE_OFFSET_BITS=64 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_POSIX_FALLOCATE=1 -I. -I../sqlite-autoconf-3380500 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_GEOPOLY -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0 -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0=/usr/src/debug/sqlite3/3_3.38.5-r0 -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot= -fdebug-prefix-map=/home/yocto/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-linux-gnueabi/sqlite3/3_3.38.5-r0/recipe-sysroot-native= -fanalyzer -DUSE_PREAD -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_BYTEORDER=1234 -c ../sqlite-autoconf-3380500/sqlite3.c  -fPIC -DPIC -o .libs/sqlite3.o
| arm-linux-gnueabi-gcc: fatal error: Killed signal terminated program cc1
| compilation terminated.
| make: *** [Makefile:547: sqlite3.lo] Error 1
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/yocto/sources/poky/meta/recipes-support/sqlite/sqlite3_3.38.5.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2134 tasks of which 2130 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 4 seconds

Summary: 1 task failed:
  /home/yocto/sources/poky/meta/recipes-support/sqlite/sqlite3_3.38.5.bb:do_compile
Summary: There were 2 ERROR messages, returning a non-zero exit code.

[log.do_compile.3072367.txt](https://github.com/priv-kweihmann/meta-sca/files/10971511/log.do_compile.3072367.txt)

**Comment by priv-kweihmann** [comment]
Thanks for the report - few things here
- when using the fanalyzer support from gcc you need an insane amount of RAM to check sqlite3 (peak on my machine 58GB of RAM were used)
- on `kirkstone` branch it is still called `SCA_BLACKLIST_gcc` not `SCA_BLOCKLIST_gcc` - I tested it and it still behaves like it should
- if you want to disable the fanalyzer feature you can as well set `SCA_GCC_ANALYZER = "0"` in your local.conf/distro.conf - this will prevent enabling the gcc flags

Over all the seen crash is not a buggy implementation of the layer, but a combination of OOM and use of wrong settings.
Feel free to reopen if any of the mentioned things don’t help on `kirkstone` branch

**Comment by Faduf** [comment]
Thanks for the feedback. I finally used the `SCA_BLACKLIST_gcc` for sqlite3.
