### ISSUE TITLE
Wrong cppcheck version

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#11258]
Hi, the recipe says it's version 2.10.9, but it's actually just 2.10 (latest tag is 2.10.2). I've noticed this when upgrading cppcheck in https://github.com/shift-left-test/meta-shift/pull/11

_Originally posted by @shr-project in https://github.com/priv-kweihmann/meta-sca/issues/10904#issuecomment-1547632540_

**Comment by shr-project** [comment]
You should also import the gcc-13 fixes from there as gcc-13 will soon land in oe-core for nanbield.
