### ISSUE TITLE
expansion of BBFILES in layer.conf hits error message triggered exception NameError: name 'oe' is not defined

### ISSUE THREAD

**Issue by mmitchel** [priv-kweihmann/meta-sca#1136]
expansion of BBFILES in layer.conf hits error message

ERROR: Unable to parse Var <BBFILES>
Traceback (most recent call last):
  File "Var <BBFILES>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable BBFILES, expression was 
...
recipes-*/*/*.bbappend which triggered exception NameError: name 'oe' is not defined

pertaining to lines 29 and 30

## Conditionally include testing recipes
BBFILES += "${@oe.utils.ifelse(d.getVar('SCA_ENABLE_TESTS') == '1', '${LAYERDIR}/recipes-sca-test/*/*.bb', '')}"
BBFILES += "${@oe.utils.ifelse(d.getVar('SCA_ENABLE_TESTS') == '1', '${LAYERDIR}/recipes-sca-test/*/*.bbappend', '')}"

commenting out the two lines allows build to process, but is obviously not the intent

**Comment by mmitchel** [comment]
SCA_ENABLE_TESTS ??= "0"

## Conditionally include testing recipes
BBFILES += "${@ '${LAYERDIR}/recipes-sca-test/*/*.bb' if d.getVar('SCA_ENABLE_TESTS') == '1' else ''}"
BBFILES += "${@ '${LAYERDIR}/recipes-sca-test/*/*.bbappend' if d.getVar('SCA_ENABLE_TESTS') == '1' else ''}"

i am using zeus tips and a specialized bsp. this appears to function, so i am not fully understanding of when BBFILES in the overall bitbake dependency calculations...

**Comment by priv-kweihmann** [comment]
I maybe be just a wild guess but can it be that `meta-sca` is included before `poky/meta` in your bblayers.conf? At least that's to me the only logical explanation for that behavior.

The used function is still present in upstream poky and I didn't see any errors of that kind in CI

**Comment by priv-kweihmann** [comment]
Anyway the code snippet you provided should do it without the need for a specific order, as it is using pure python.
But now that I think about it, I will restructure it using a different approach - thanks for pointing that out
