### ISSUE TITLE
cve-update-db-native.bbappend file error

### ISSUE THREAD

**Issue by memrekaraaslan** [priv-kweihmann/meta-sca#1157]
I am using thud version of Yocto and I followed meta-sca as it wrote in the guide. I cloned the master and went into it and pulled it into thud branch. I also added this layer to the bblayers file. When I enter the bitbake core-image-minimal command, I get an error like the following:

```
> hie @ ubuntu: ~ / mender-variscite-thud / sources $ bitbake core-image-minimal
> Loading cache: 100% | ############################################# ################################################## ################################################## ############################## | Time: 0:00:02
> Loaded 4226 entries from dependency cache.
> ERROR: No recipes available for:
>   /home/hie/mender-variscite-thud/sources/meta-sca/recipes-devtools/cve-update-db-native/cve-update-db-native.bbappend
> 
> Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

When I examine the layers, I see that the cve-update-db-native.bb file does not exist. I think I get the error from this. I am stuck because I have limited yocto knowledge. How should I go to add this meta-sca layer to my yocto system?

**Comment by priv-kweihmann** [comment]
To me it seems you're not on the latest available thud.
Because https://git.yoctoproject.org/cgit/cgit.cgi/poky/log/meta/recipes-core/meta/cve-update-db-native.bb?h=thud shows that the file does exist, although not for a long time.

It was on of the "christmas gifts" from the project ;-).

If you're not able to change the thud version, you can add `BB_DANGLINGAPPENDS_WARNONLY = "1"` (https://www.yoctoproject.org/docs/current/bitbake-user-manual/bitbake-user-manual.html#var-bb-BB_DANGLINGAPPENDS_WARNONLY) to your local.conf or better distro.conf and the error will be converted into a warning, so you're able to build again

**Comment by priv-kweihmann** [comment]
To answer your question, I would propose you update you thud branch to the latest available - if that doesn't work use the work around (BB_DANGLING...) - I don't see the need to write a recipe for that yourself

**Comment by memrekaraaslan** [comment]
Okey thanks for speedy reply. I'm trying now and I'll give feedback here

**Comment by memrekaraaslan** [comment]
I did as you said the second and changed the error to a warning. Then I ran the command "bitbake core-image-minimal". But I got many different mistakes. The copy is below.

```
ERROR: ruby-thread-safe-native-0.3.6-r0 do_unpack_gem: Function failed: do_unpack_gem (log file is located at / home / hie / mender-variscite-thud / build / tmp / work / x86_64-linux / ruby- thread-safe-native / 0.3.6-r0 / temp / lo g.do_unpack_gem.5524)
ERROR: ruby-descendants-tracker-native-0.0.4-r0 do_unpack_gem: Function failed: do_unpack_gem (log file is located at / home / hie / mender-variscite-thud / build / tmp / work / x86_64-linux / ruby- descendants-tracker-native / 0.0.4-r0 / temp / log.do_unpack_gem.5525)
ERROR: Logfile of failure stored in: /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-thread-safe-native/0.3.6-r0/temp/log.do_unpack_gem.5524
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual: native: /home/hie/mender-variscite-thud/sources/poky/meta/recipes-devtools/ruby/ruby_2.5.3.bb: do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['ruby-native', 'openssl-native', 'automake-native', 'libtool-native', 'autoconf-native', 'gnu-config-native', 'libyaml -native ',' quilt-native ',' texinfo-dummy-nat ive ',' m4-native ']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_unpack_gem
| ERROR: While executing gem ... (Errno :: ENOENT)
| No such file or directory @ realpath_rec - /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-thread-safe-native/0.3.6-r0/thread_safe-0.3.6/. RSpec
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_unpack_gem (log file is located at /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-thread-safe-native/0.3.6-r0/temp/log .do_unpack_gem.5524)
ERROR: Logfile of failure stored in: /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-descendants-tracker-native/0.0.4-r0/temp/log.do_unpack_gem.5525
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual: native: /home/hie/mender-variscite-thud/sources/poky/meta/recipes-devtools/ruby/ruby_2.5.3.bb: do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['ruby-native', 'openssl-native', 'automake-native', 'libtool-native', 'autoconf-native', 'gnu-config-native', 'libyaml -native ',' quilt-native ',' texinfo-dummy-nat ive ',' m4-native ']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_unpack_gem
| ERROR: While executing gem ... (Errno :: ENOENT)
| No such file or directory @ realpath_rec - /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-descendants-tracker-native/0.0.4-r0/descendants_tracker-0.0.4/. gitignor to
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_unpack_gem (log file is located at /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/ruby-descendants-tracker-native/0.0.4-r0/temp/log .do_unpack_gem.5525)
ERROR: Task (/home/hie/mender-variscite-thud/sources/meta-sca/recipes-ruby/ruby-descendants-tracker-native/ruby-descendants-tracker-native_0.0.4.bb:do_unpack_gem) failed with exit code '1'
ERROR: Task (/home/hie/mender-variscite-thud/sources/meta-sca/recipes-ruby/ruby-thread-safe-native/ruby-thread-safe-native_0.3.6.bb:do_unpack_gem) failed with exit code '1'
NOTE: Tasks Summary: Attempted 515 tasks of which 470 didn't need to be rerun and 2 failed.
NOTE: Writing buildhistory

Summary: 2 tasks failed:
  I /home/hie/mender-variscite-thud/sources/meta-sca/recipes-ruby/ruby-descendants-tracker-native/ruby-descendants-tracker-native_0.0.4.bb:do_unpack_ge
  I /home/hie/mender-variscite-thud/sources/meta-sca/recipes-ruby/ruby-thread-safe-native/ruby-thread-safe-native_0.3.6.bb:do_unpack_ge
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

```
I think this will force me too much. I just want to check the binary files running on my embedded device. Can I integrate the layer only accordingly? Thank you

**Comment by priv-kweihmann** [comment]
Okay ruby errors - never seen them before.
Did you read the [getting started guide](https://github.com/priv-kweihmann/meta-sca/blob/master/docs/getting_started.md)? Esp. in https://github.com/priv-kweihmann/meta-sca/blob/master/docs/getting_started.md#what-do-i-need  - did execute the `configure` script?
I guess you're not looking for `ruby` support, right? Then it would be perfectly fine to disable it.

If you want to run ruby check, please open a new bug and put all the needed infos there, as the original reported bug seems to be solved.

**Comment by priv-kweihmann** [comment]
And while you're at it, please attach the logfiles mentioned in the console printout to a (potential) new bug - as the poky build console does offer much insights what really went wrong

**Comment by memrekaraaslan** [comment]
My existing build files for Yocto worked without the meta-sca layer.
https://github.com/priv-kweihmann/meta-sca/blob/master/docs/getting_started.md#what-do-i-need
I downloaded the necessary files in this manual. Then I ran this command in the / source directory in the existing Yocto:

> git clone https://github.com/priv-kweihmann/meta-sca.git meta-sca

Then I entered the meta-sca layer and executed "git checkout origin / thud" command and pulled it to thud branch. Then I added the layer to the bblayers file and executed the necessary setup by running the "configure" script. I added it to "local.conf" file as follows:

> INHERIT + = "sca"

Then I tried to make an image, but as you can see, I got errors.

**Comment by memrekaraaslan** [comment]
I removed the ruby recipe from the file /conf/layer.conf. But nothing has changed.

/meta-sca/conf/layer.conf:
             ...
             $ {LAYERDIR} / recipes-python / * / *. Bb \
             $ {LAYERDIR} / recipes-python / * / *. Bbappend \
             //${LAYERDIR{/recipes-ruby/*/*.bb \
             //${LAYERDIR{/recipes-ruby/*/*.bbappend \
             $ {LAYERDIR} / recipes-sca-rules / * / *. Bb \
             $ {LAYERDIR} / recipes-sca-rules / * / *. Bbappend \
             ...

I made the ruby recipes here into the comments line. The error I received has not changed again. I even deleted the complete dependencies of the recipe. Unfortunately :(

**Comment by priv-kweihmann** [comment]
Disabling the ruby integration shouldn't be done with deleting stuff from the layer.conf.
Just add the following to your  local.conf
```
SCA_AVAILABLE_MODULES = "\
                          alexkohler \
                          ansible \
                          ansiblelint \
                          ansibleroles \
                          bandit \
                          bashate \
                          bitbake \
                          cbmc \
                          checkbashism \
                          configcheck \
                          cppcheck \
                          cpplint \
                          cspell \
                          darglint \
                          dennis \
                          detectsecrets \
                          eslint \
                          flake8 \
                          flawfinder \
                          flint \
                          gcc \
                          gixy \
                          golint \
                          gosec \
                          govet \
                          htmlhint \
                          jshint \
                          jsonlint \
                          kconfighard \
                          looong \
                          lynis \
                          msgcheck \
                          mypy \
                          nixauditor \
                          npmaudit \
                          oelint \
                          perl \
                          perlcritic \
                          pkgqaenc \
                          proselint \
                          pscan \
                          pyfindinjection \
                          pylint \
                          pyright \
                          pysymcheck \
                          pytype \
                          rats \
                          reconbf \
                          retire \
                          revive \
                          safety \
                          setuptoolslint \
                          shellcheck \
                          slick \
                          sparse \
                          splint \
                          standard \
                          stank \
                          stylelint \
                          sudokiller \
                          systemdlint \
                          textlint \
                          tiger \
                          tscancode \
                          upc \
                          vulture \
                          wotan \
                          xmllint \
                          yamllint \
                          yara \
                          zrd \
                        "
```

and all ruby code will be disabled - and if it is disabled it won't get executed

**Comment by memrekaraaslan** [comment]
I did as you said, but now I got an error like below: 

`Initialising tasks: 100% |#########################################################################| Time: 0:00:23
Sstate summary: Wanted 1487 Found 1 Missed 1486 Current 248 (0% match, 14% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: golang.org-lib-native-20190724-r0 do_compile: Function failed: do_compile (log file is located at /home/hie                                                                                                                        /mender-variscite-thud/build/tmp/work/x86_64-linux/golang.org-lib-native/20190724-r0/temp/log.do_compile.14072)
ERROR: Logfile of failure stored in: /home/hie/mender-variscite-thud/build/tmp/work/x86_64-linux/golang.org-lib-na                                                                                                                        tive/20190724-r0/temp/log.do_compile.14072
Log data follows:
| DEBUG: Executing shell function do_compile
| errors
| internal/race
| runtime/internal/atomic
| runtime/internal/sys
| internal/cpu
| sync/atomic
| unicode
| unicode/utf8
| internal/testlog
| internal/bytealg
| math
| math/bits
| crypto/internal/subtle
| crypto/subtle
| container/list
| runtime
| vendor/golang_org/x/crypto/cryptobyte/asn1
| internal/nettrace
| vendor/golang_org/x/net/dns/dnsmessage
| runtime/cgo
| strconv
| vendor/golang_org/x/crypto/curve25519
| encoding
| unicode/utf16
| sync
| golang.org/x/crypto/cast5
| golang.org/x/crypto/internal/subtle
| io
| syscall
| reflect
| bytes
| hash
| crypto
| crypto/cipher
| math/rand
| strings
| time
| internal/poll
| crypto/aes
| internal/syscall/unix
| encoding/binary
| crypto/internal/randutil
| bufio
| os
| crypto/des
| crypto/hmac
| crypto/md5
| crypto/rc4
| fmt
| crypto/sha1
| crypto/sha256
| crypto/sha512
| encoding/base64
| sort
| internal/singleflight
| vendor/golang_org/x/crypto/internal/chacha20
| vendor/golang_org/x/crypto/poly1305
| hash/crc32
| encoding/pem
| path/filepath
| io/ioutil
| path
| context
| math/big
| encoding/hex
| vendor/golang_org/x/text/transform
| vendor/golang_org/x/crypto/chacha20poly1305
| net
| net/url
| encoding/json
| compress/flate
| crypto/elliptic
| crypto/rand
| crypto/dsa
| compress/gzip
| log
| vendor/golang_org/x/text/unicode/bidi
| encoding/asn1
| crypto/rsa
| vendor/golang_org/x/text/secure/bidirule
| vendor/golang_org/x/net/http2/hpack
| crypto/ecdsa
| crypto/x509/pkix
| vendor/golang_org/x/text/unicode/norm
| mime
| mime/quotedprintable
| vendor/golang_org/x/crypto/cryptobyte
| net/http/internal
| golang.org/x/text/transform
| golang.org/x/text/unicode/bidi
| golang.org/x/text/unicode/norm
| golang.org/x/text/secure/bidirule
| flag
| golang.org/x/net/idna
| golang.org/x/sys/cpu
| vendor/golang_org/x/net/idna
| golang.org/x/crypto/blowfish
| golang.org/x/crypto/blake2b
| golang.org/x/crypto/bcrypt
| golang.org/x/crypto/blake2s
| golang.org/x/crypto/argon2
| golang.org/x/crypto/bn256
| golang.org/x/crypto/poly1305
| golang.org/x/crypto/cryptobyte/asn1
| golang.org/x/crypto/internal/chacha20
| golang.org/x/crypto/cryptobyte
| golang.org/x/crypto/curve25519
| golang.org/x/crypto/chacha20poly1305
| golang.org/x/crypto/ed25519/internal/edwards25519
| golang.org/x/crypto/hkdf
| golang.org/x/crypto/md4
| golang.org/x/crypto/nacl/auth
| golang.org/x/crypto/ed25519
| golang.org/x/crypto/salsa20/salsa
| golang.org/x/crypto/openpgp/errors
| golang.org/x/crypto/openpgp/armor
| golang.org/x/crypto/nacl/sign
| compress/bzip2
| hash/adler32
| compress/zlib
| golang.org/x/crypto/openpgp/elgamal
| golang.org/x/crypto/openpgp/s2k
| image/color
| golang.org/x/crypto/otr
| golang.org/x/crypto/pbkdf2
| golang.org/x/crypto/pkcs12/internal/rc2
| golang.org/x/crypto/ripemd160
| golang.org/x/crypto/scrypt
| golang.org/x/crypto/sha3
| golang.org/x/crypto/nacl/secretbox
| golang.org/x/crypto/nacl/box
| golang.org/x/crypto/salsa20
| golang.org/x/sys/unix
| golang.org/x/crypto/ssh/test
| image
| golang.org/x/crypto/tea
| golang.org/x/crypto/twofish
| golang.org/x/crypto/xtea
| golang.org/x/crypto/xts
| go/token
| golang.org/x/crypto/ssh/terminal
| image/internal/imageutil
| text/tabwriter
| go/scanner
| image/jpeg
| container/heap
| golang.org/x/crypto/openpgp/packet
| go/ast
| go/constant
| golang.org/x/crypto/openpgp
| go/parser
| go/printer
| regexp/syntax
| vendor/golang_org/x/net/http/httpproxy
| golang.org/x/tools/go/ast/astutil
| crypto/x509
| net/textproto
| go/types
| vendor/golang_org/x/net/http/httpguts
| mime/multipart
| golang.org/x/crypto/openpgp/clearsign
| regexp
| text/template/parse
| crypto/tls
| golang.org/x/crypto/ocsp
| golang.org/x/crypto/pkcs12
| golang.org/x/crypto/ssh
| text/template
| go/doc
| net/http/httptrace
| net/http
| os/exec
| text/scanner
| golang.org/x/mod/semver
| golang.org/x/mod/module
| go/build
| golang.org/x/mod/sumdb/note
| golang.org/x/mod/sumdb/tlog
| golang.org/x/crypto/ssh/agent
| archive/zip
| golang.org/x/crypto/ssh/knownhosts
| runtime/debug
| golang.org/x/tools/go/internal/gcimporter
| runtime/trace
| testing
| golang.org/x/mod/sumdb/dirhash
| golang.org/x/net/bpf
| golang.org/x/net/context
| golang.org/x/net/dict
| golang.org/x/net/dns/dnsmessage
| golang.org/x/mod/sumdb/storage
| golang.org/x/net/html/atom
| golang.org/x/net/html
| golang.org/x/tools/go/gcexportdata
| golang.org/x/lint
| golang.org/x/text/encoding/internal/identifier
| golang.org/x/text/encoding
| golang.org/x/text/encoding/internal
| golang.org/x/text/encoding/charmap
| golang.org/x/lint/golint
| golang.org/x/text/encoding/japanese
| golang.org/x/text/encoding/korean
| golang.org/x/text/encoding/simplifiedchinese
| golang.org/x/text/encoding/traditionalchinese
| golang.org/x/crypto/acme
| net/http/httptest
| golang.org/x/mod/sumdb
| golang.org/x/crypto/acme/autocert
| golang.org/x/net/context/ctxhttp
| golang.org/x/mod/gosumcheck
| golang.org/x/text/internal/utf8internal
| golang.org/x/text/runes
| golang.org/x/crypto/acme/autocert/internal/acmetest
| golang.org/x/text/internal/tag
| golang.org/x/text/encoding/unicode
| golang.org/x/text/internal/language
| golang.org/x/net/http/httpguts
| golang.org/x/net/http/httpproxy
| golang.org/x/net/http2/hpack
| golang.org/x/net/internal/iana
| golang.org/x/net/internal/socket
| golang.org/x/net/http2
| golang.org/x/net/ipv4
| golang.org/x/text/internal/language/compact
| golang.org/x/text/language
| golang.org/x/net/ipv6
| golang.org/x/text/encoding/htmlindex
| golang.org/x/net/html/charset
| golang.org/x/net/internal/socks
| golang.org/x/net/nettest
| golang.org/x/net/icmp
| golang.org/x/net/internal/sockstest
| golang.org/x/net/internal/timeseries
| golang.org/x/net/netutil
| golang.org/x/net/proxy
| net/http/cookiejar
| html
| golang.org/x/net/publicsuffix
| encoding/xml
| html/template
| golang.org/x/net/webdav/internal/xml
| golang.org/x/net/http2/h2c
| golang.org/x/net/http2/h2i
| golang.org/x/net/trace
| golang.org/x/net/websocket
| golang.org/x/net/webdav
| golang.org/x/net/xsrftoken
| golang.org/x/sync/errgroup
| golang.org/x/sync/semaphore
| golang.org/x/sync/singleflight
| golang.org/x/sync/syncmap
| golang.org/x/term
| golang.org/x/text
| golang.org/x/text/internal
| # golang.org/x/term
| src/golang.org/x/term/term_linux.go:11:7: ioctlReadTermios redeclared in this block
|       previous declaration at src/golang.org/x/term/term_aix.go:11:26
| go/format
| golang.org/x/text/cases
| golang.org/x/text/internal/colltab
| golang.org/x/text/internal/catmsg
| golang.org/x/text/collate
| golang.org/x/text/internal/stringset
| golang.org/x/text/internal/number
| golang.org/x/text/message/catalog
| golang.org/x/text/internal/format
| encoding/gob
| golang.org/x/text/feature/plural
| golang.org/x/text/unicode/cldr
| hash/fnv
| golang.org/x/tools/go/types/typeutil
| golang.org/x/tools/go/buildutil
| golang.org/x/tools/go/ssa
| golang.org/x/tools/go/internal/cgo
| golang.org/x/tools/go/loader
| golang.org/x/tools/go/internal/packagesdriver
| golang.org/x/tools/internal/fastwalk
| golang.org/x/tools/internal/gopathwalk
| golang.org/x/tools/internal/semver
| golang.org/x/tools/go/packages
| golang.org/x/text/message
| golang.org/x/text/cmd/gotext/examples/extract
| golang.org/x/text/cmd/gotext/examples/extract_http/pkg
| golang.org/x/text/cmd/gotext/examples/extract_http
| golang.org/x/tools/go/callgraph
| golang.org/x/tools/go/ssa/ssautil
| golang.org/x/text/internal/gen
| golang.org/x/text/cmd/gotext/examples/rewrite
| golang.org/x/tools/go/callgraph/cha
| golang.org/x/text/collate/build
| golang.org/x/text/message/pipeline
| golang.org/x/text/cmd/gotext
| runtime/pprof
| golang.org/x/text/collate/tools/colcmp
| golang.org/x/text/currency
| golang.org/x/text/internal/cldrtree
| golang.org/x/text/encoding/ianaindex
| golang.org/x/text/encoding/internal/enctest
| golang.org/x/text/encoding/unicode/utf32
| golang.org/x/text/internal/export/idna
| golang.org/x/text/date
| golang.org/x/text/internal/export/unicode
| golang.org/x/text/internal/gen/bitfield
| golang.org/x/text/internal/testtext
| hash/crc64
| golang.org/x/text/internal/triegen
| golang.org/x/text/internal/ucd
| golang.org/x/text/number
| golang.org/x/text/language/display
| golang.org/x/text/search
| golang.org/x/text/secure
| golang.org/x/text/width
| golang.org/x/text/unicode
| golang.org/x/text/unicode/rangetable
| golang.org/x/text/unicode/runenames
| golang.org/x/text/secure/precis
| golang.org/x/tools/blog/atom
| golang.org/x/tools/present
| golang.org/x/tools/benchmark/parse
| golang.org/x/tools/cmd/auth/authtest
| golang.org/x/tools/cmd/auth/cookieauth
| golang.org/x/tools/blog
| golang.org/x/tools/cmd/auth/gitauth
| golang.org/x/tools/cmd/auth/netrcauth
| golang.org/x/tools/cmd/benchcmp
| golang.org/x/tools/cmd/bundle
| golang.org/x/tools/go/callgraph/rta
| golang.org/x/tools/go/callgraph/static
| golang.org/x/tools/container/intsets
| golang.org/x/tools/cmd/compilebench
| golang.org/x/tools/go/pointer
| golang.org/x/tools/cover
| golang.org/x/tools/cmd/cover
| golang.org/x/tools/cmd/digraph
| golang.org/x/tools/cmd/callgraph
| golang.org/x/tools/refactor/eg
| golang.org/x/tools/cmd/eg
| golang.org/x/tools/cmd/fiximports
| os/user
| golang.org/x/tools/cmd/getgo/server
| golang.org/x/tools/cmd/go-contrib-init
| debug/dwarf
| go/internal/gcimporter
| archive/tar
| go/internal/srcimporter
| expvar
| debug/elf
| golang.org/x/tools/godoc/analysis
| golang.org/x/tools/cmd/getgo
| golang.org/x/tools/godoc/golangorgenv
| go/internal/gccgoimporter
| golang.org/x/tools/godoc/vfs
| golang.org/x/tools/godoc/util
| golang.org/x/tools/godoc/vfs/httpfs
| index/suffixarray
| go/importer
| golang.org/x/tools/cmd/godex
| golang.org/x/tools/godoc
| golang.org/x/tools/godoc/redirect
| golang.org/x/tools/godoc/static
| golang.org/x/tools/godoc/vfs/gatefs
| golang.org/x/tools/godoc/vfs/mapfs
| golang.org/x/tools/godoc/vfs/zipfs
| golang.org/x/tools/playground
| net/http/pprof
| golang.org/x/tools/internal/module
| golang.org/x/tools/internal/imports
| golang.org/x/tools/cmd/godoc
| golang.org/x/tools/refactor/importgraph
| golang.org/x/tools/refactor/satisfy
| golang.org/x/tools/refactor/rename
| golang.org/x/tools/cmd/gomvpkg
| golang.org/x/tools/cmd/guru/serial
| golang.org/x/tools/internal/jsonrpc2
| golang.org/x/tools/cmd/goimports
| golang.org/x/tools/internal/lsp/telemetry/stats
| golang.org/x/tools/internal/lsp/telemetry/worker
| golang.org/x/tools/internal/lsp/telemetry/tag
| golang.org/x/tools/internal/lsp/telemetry
| golang.org/x/tools/internal/lsp/telemetry/log
| golang.org/x/tools/internal/lsp/telemetry/metric
| golang.org/x/tools/internal/lsp/telemetry/trace
| golang.org/x/tools/internal/span
| golang.org/x/tools/internal/lsp/debug
| golang.org/x/tools/internal/xcontext
| golang.org/x/tools/internal/lsp/protocol
| golang.org/x/tools/go/analysis
| golang.org/x/tools/go/analysis/passes/internal/analysisutil
| golang.org/x/tools/go/analysis/passes/asmdecl
| golang.org/x/tools/go/ast/inspector
| golang.org/x/tools/go/analysis/passes/inspect
| golang.org/x/tools/go/analysis/passes/assign
| golang.org/x/tools/go/analysis/passes/atomic
| golang.org/x/tools/go/analysis/passes/atomicalign
| golang.org/x/tools/go/analysis/passes/bools
| golang.org/x/tools/go/analysis/passes/buildtag
| golang.org/x/tools/go/analysis/passes/cgocall
| golang.org/x/tools/go/analysis/passes/composite
| golang.org/x/tools/go/analysis/passes/copylock
| golang.org/x/tools/go/analysis/passes/httpresponse
| golang.org/x/tools/go/analysis/passes/loopclosure
| golang.org/x/tools/go/cfg
| golang.org/x/tools/go/analysis/passes/nilfunc
| golang.org/x/tools/go/analysis/passes/printf
| golang.org/x/tools/go/analysis/passes/shift
| golang.org/x/tools/go/analysis/passes/stdmethods
| golang.org/x/tools/go/analysis/passes/ctrlflow
| golang.org/x/tools/go/analysis/passes/structtag
| golang.org/x/tools/go/analysis/passes/lostcancel
| golang.org/x/tools/go/analysis/passes/tests
| golang.org/x/tools/go/analysis/passes/unmarshal
| golang.org/x/tools/go/analysis/passes/unreachable
| golang.org/x/tools/go/analysis/passes/unsafeptr
| golang.org/x/tools/go/analysis/passes/unusedresult
| golang.org/x/tools/internal/lsp/diff
| golang.org/x/tools/internal/lsp/fuzzy
| golang.org/x/tools/internal/lsp/snippet
| golang.org/x/tools/internal/lsp/browser
| golang.org/x/tools/internal/memoize
| golang.org/x/tools/internal/lsp/telemetry/ocagent/wire
| golang.org/x/tools/internal/tool
| golang.org/x/tools/internal/lsp/source
| golang.org/x/tools/cmd/gorename
| golang.org/x/tools/internal/lsp/telemetry/ocagent
| golang.org/x/tools/cmd/gotype
| golang.org/x/tools/cmd/goyacc
| golang.org/x/tools/internal/lsp
| golang.org/x/tools/internal/lsp/cache
| golang.org/x/tools/imports
| golang.org/x/tools/cmd/guru
| golang.org/x/tools/cmd/html2article
| golang.org/x/tools/playground/socket
| golang.org/x/tools/cmd/present
| golang.org/x/tools/internal/lsp/cmd
| golang.org/x/tools/cmd/gopls
| golang.org/x/tools/cmd/splitdwarf/internal/macho
| golang.org/x/tools/cmd/splitdwarf
| golang.org/x/tools/go/ssa/interp
| golang.org/x/tools/cmd/stress
| golang.org/x/tools/cmd/stringer
| golang.org/x/tools/cmd/toolstash
| golang.org/x/tools/cmd/ssadump
| golang.org/x/tools/go/analysis/internal/analysisflags
| golang.org/x/tools/go/types/objectpath
| golang.org/x/tools/go/analysis/internal/checker
| golang.org/x/tools/go/analysis/passes/errorsas
| golang.org/x/tools/go/analysis/passes/buildssa
| golang.org/x/tools/go/analysis/internal/facts
| golang.org/x/tools/go/analysis/passes/deepequalerrors
| golang.org/x/tools/go/analysis/passes/findcall
| golang.org/x/tools/go/analysis/passes/nilness
| golang.org/x/tools/go/analysis/analysistest
| golang.org/x/tools/go/analysis/unitchecker
| golang.org/x/tools/go/analysis/passes/pkgfact
| golang.org/x/tools/go/analysis/multichecker
| golang.org/x/tools/go/analysis/singlechecker
| golang.org/x/tools/go/analysis/cmd/vet
| golang.org/x/tools/go/analysis/passes/findcall/cmd/findcall
| golang.org/x/tools/go/analysis/passes/lostcancel/cmd/lostcancel
| golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness
| golang.org/x/tools/go/analysis/passes/shadow
| golang.org/x/tools/go/analysis/passes/unmarshal/cmd/unmarshal
| golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
| golang.org/x/tools/go/expect
| golang.org/x/tools/go/internal/gccgoimporter
| golang.org/x/tools/go/gccgoexportdata
| golang.org/x/tools/go/packages/gopackages
| golang.org/x/tools/go/packages/packagestest
| golang.org/x/tools/go/vcs
| golang.org/x/tools/gopls
| golang.org/x/tools/internal/apidiff
| golang.org/x/tools/internal/txtar
| golang.org/x/tools/internal/lsp/tests
| golang.org/x/xerrors/internal
| golang.org/x/xerrors
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/hie/mender-variscite-thud/build/tmp/work/x86_64                                                                                                                        -linux/golang.org-lib-native/20190724-r0/temp/log.do_compile.14072)
ERROR: Task (/home/hie/mender-variscite-thud/sources/meta-sca/recipes-go/golang.org-lib-native/golang.org-lib-nati                                                                                                                        ve_20190724.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 864 tasks of which 553 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory

Summary: 1 task failed:
  /home/hie/mender-variscite-thud/sources/meta-sca/recipes-go/golang.org-lib-native/golang.org-lib-native_20190724                                                                                                                        .bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.`

**Comment by memrekaraaslan** [comment]
Do you have any idea about this error ? @priv-kweihmann

**Comment by priv-kweihmann** [comment]
Actually yes - it should have been fixed recently (changeset from 2020/04/18). Try updating the meta-sca layer.

**Comment by memrekaraaslan** [comment]
I am trying now

**Comment by memrekaraaslan** [comment]
No, same problem persist

**Comment by priv-kweihmann** [comment]
Another option would be to do `git reset --hard ce8825a3680e599ed98a5a8e644687bbc31ed070` in the layer repository - that is the last known good revision where I'm sure that it worked in CI

**Comment by priv-kweihmann** [comment]
Fixed in thud.
For any further issue, please open a new bug report
