### ISSUE TITLE
python3-pyflakes-native 2.2.0 is incompatible with python3-flake8-native 3.7.9

### ISSUE THREAD

**Issue by nzottmann** [priv-kweihmann/meta-sca#1197]
**Describe the bug**
As described in #1122, python3-pyflakes-native was updated from 2.1.1 to 2.2.0 in cac73afb4ad452416c448f23454f9b56f0216a15. 

But python3-flake8-native 3.7.9 depends on `pyflakes >= 2.1.0, < 2.2.0`, which does not include 2.2.0 (see https://gitlab.com/pycqa/flake8/-/blob/3.7.9/setup.cfg#L16)

flake8 supports pyflakes 2.2.0 in version 3.8.0, which is currently in alpha status and not released yet.

**Used layer**
- meta-sca: f41470d4ca66e1b3abc6ae174845a229f6a61319 (current warrior at time of writing)

**Additional**
I discovered this while creating a recipe which needs
```
DEPENDS = "python3-flake8-native python3-pyflakes-native"
```
It failed with
```
| pkg_resources.DistributionNotFound: The 'pyflakes<2.2.0,>=2.1.0' distribution was not found and is required by flake8
```

It works fine with 40a5bc949e2cb53e43f7cea541ce85f806733e72 and fails from 611177cc4ee69183fcf40b374c28759aa571e9f9 on.

**Comment by priv-kweihmann** [comment]
Thanks for pointing that out - will revert to the version before
