### ISSUE TITLE
scarthgap compatibility

### ISSUE THREAD

**Issue by rarengifoArthrex** [priv-kweihmann/meta-sca#12087]
scarthgap has been released and it would be good to have a branch here for it.

**Comment by priv-kweihmann** [comment]
What's the use in an unmaintained branch?
So far nobody stepped up to maintain one and I am no going to maintain it (see https://github.com/priv-kweihmann/meta-sca/discussions/8723).

I'm going to keep the ticket open in case someone wants to do it

**Comment by rarengifoArthrex** [comment]
ahh ok scarthgap is the new lts but was talking to my team internally and i think we will be using master.  Also will try to help when i can on this.  Thanks for doing this!

**Comment by clementperon** [comment]
@priv-kweihmann the branch can still give the last valid commit to use for this version.
Also it will keep the recipes listed in https://layers.openembedded.org/

**Comment by priv-kweihmann** [comment]
@clementperon if you propose something, be my guest - but I have little interest in it, unless if it keeps being unmaintained

**Comment by clementperon** [comment]
@priv-kweihmann just push a branch "scarthgap" with the commit ae7c5f03ccf7b01195ce1a292d7a48fd272f4574

It's the latest commit before the compat layer is dropped

**Comment by priv-kweihmann** [comment]
@clementperon so you are going to take over maintainership for that branch? 😉.
If not, I will schedule such a branch when I'll find the time and motivation

**Comment by clementperon** [comment]
Branch doesn't mean it's active and maintained.

Just it points to the last commit valid for this release

**Comment by priv-kweihmann** [comment]
@clementperon I see no point in that.
If you want a certain compat level, just pin the commit.
I will not do it for the sake of it, esp if it's going to be unmaintained.

I consider this issue closed now
