### ISSUE TITLE
OELint: Propagate SCA findings inside classes as well

### ISSUE THREAD

**Issue by pasweistorz** [priv-kweihmann/meta-sca#12289]
Hi,

**Is your feature request related to a problem? Please describe.**
We are using the OELint from the meta-sca layer. We can see that the `.raw` text files deployed to `${DEPLOY_DIR_IMAGE}/${MACHINE}/sca/oelint/raw` contain findings triggered by code in classes coming from the same layer as the recipe. But those findings aren't considered being errors. Is there a reason that findings from classes aren't considered being errors? Would it be possible to implement that? Maybe not per default but via a variable that could be turned on?

Thanks for investigating.

**Comment by priv-kweihmann** [comment]
That's indeed a bug... Will fix that in the next couple of days
