### ISSUE TITLE
Use pfff as tool

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#126]
Maybe https://github.com/facebook/pfff is worth a look, as it seems to support a variety of languages

**Comment by priv-kweihmann** [comment]
According to this https://github.com/facebook/pfff/issues/158#issuecomment-395988221 pfff doesn't seem to be under active development anymore. Also this project does have major version constraints when using opam. After a deeper look into the actual performed check. I decided to close this issue as the effort does weight up the benefit of this tool.

**Comment by daghan** [comment]
Hi @priv-kweihmann,
We noticed that you closed this issue because pfff is no longer maintained. In fact, the core developer for pfff is with [us](https://r2c.dev) and we are actively maintaining [sgrep.](https://github.com/returntocorp/sgrep)

**Comment by priv-kweihmann** [comment]
@daghan thanks for letting me know - still the other points to remain, like version constraints - or did that change?
Or did you just trying to advertise sgrep to me ;-)?

**Comment by aryx** [comment]
the constraint right now is to use ocaml < ocaml 4.07 but there's a ticket to remove the use of camlp4 which would allow to use ocaml > 4.07 too

**Comment by priv-kweihmann** [comment]
If I ever going to include any ocaml based tool, it has to come up with support of the latest stable branch (afaik 4.09)

**Comment by aryx** [comment]
FYI I've just updated pfff to work with recent OCaml versions, including OCaml 4.10.0.
there's a new OPAM package that just got merged here: https://github.com/ocaml/opam-repository/pull/16125

**Comment by priv-kweihmann** [comment]
Thanks - that leaves me only with the burden of integrating ocaml into yocto;-)
