### ISSUE TITLE
Decrease the size of the layer

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#1853]
Currently a full git clone of the layer is fairly big - try to decrease the size of it

**Comment by bachp** [comment]
@priv-kweihmann The repository size containing many tarballs is currently our main concern against using meta-sca in all our projects.

**Comment by priv-kweihmann** [comment]
@bachp I fully understand your concerns, but so far I couldn't figure out how to remove the tarballs from history without changing the commit shas of HEAD and any tag release.
Unfortunately I have to preserve history, as many people rely on that.

Maybe my git foo isn't strong enough, so I'm open for pointers, ideas a.s.o. - so far the only thing that came to my mind in a fork or a branch-off where the offending commits could be dropped

**Comment by bachp** [comment]
@priv-kweihmann Unfortunately I think there is no way to reduce the size without rewriting the history. Creating a new fork and cleaning that up is probably the only option.

**Comment by priv-kweihmann** [comment]
Yeah :-( - I will keep thinking about, how to add a "minified" version of meta-sca to some place.
Depending on what tool you use for settings up your layer stack (kas, repo, a.s.o.) also a `git clone --depth=1` might be a viable option till I can come up with the mentioned fork

**Comment by priv-kweihmann** [comment]
Releases starting from v1.24.0 are now available at meta-sca-minified
