### ISSUE TITLE
staging.bbclass from poky/meta? not found

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#187]
Here is the patch:

`diff --git a/classes/staging.bbclass b/classes/staging.bbclass
index 6eb5e78..512fd00 100644
--- a/classes/staging.bbclass
+++ b/classes/staging.bbclass
@@ -28,7 +28,7 @@ def get_rel_path(d, _file):
         res = os.path.relpath(x, os.path.join(get_path_for_layer(d, "meta-sca"), "classes/staging.bbclass"))
     return res
 
-require ${@get_rel_path(d, "staging.bbclass")}
+require ${@get_rel_path(d, "meta/classes/staging.bbclass")}
 
 ## This class does override parts of the original poky implementation
 ## of staging.bbclass
`

**Comment by RobertBerger** [comment]
@priv-kweihmann  So you say if you apply this patch you see the "other error"?

**Comment by RobertBerger** [comment]
@priv-kweihmann In my case I have to fix this one first. Without my patch it won't do anything else. It's stuck there because it can not find the file.

**Comment by priv-kweihmann** [comment]
@RobertBerger could please post the content of your bblayers.conf and I'll have a look at the issue in detail later

**Comment by RobertBerger** [comment]
@priv-kweihmann You can get even more if you want and if you have free space on your disk;)

```
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/student/projects/resy-playground/sources/poky/meta \
  /home/student/projects/resy-playground/sources/poky/meta-poky \
  /home/student/projects/resy-playground/sources/poky/meta-yocto-bsp \
  /home/student/projects/resy-playground/sources/poky/../meta-resy \
  /home/student/projects/resy-playground/sources/poky/../meta-desire \
  /home/student/projects/resy-playground/sources/poky/../meta-openembedded/meta-oe \
  /home/student/projects/resy-playground/sources/poky/../meta-openembedded/meta-python \  
  /home/student/projects/resy-playground/sources/poky/../meta-sca \
  /home/student/projects/resy-playground/sources/poky/../meta-clang \
  "
```

If you would like the full project I can provide this as well.

... or ...

I guess I could also give you access to my server (in Austria) where I play with this stuff and show you what's happening.

I currently sit in Athens/Greece.

Whatever you like. Fastest would be to arrange some date/time and a remote session if you are interested.

**Comment by priv-kweihmann** [comment]
Yeah a remote session would be nice, as I don't quite know how your previous fix and this issue here play together. What time/date does fit best for you?
Maybe just send me a mail to discuss this further...
