### ISSUE TITLE
ERROR: POPULATESYSROOTDEPS does not contain exactly one ':' character.

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#188]
`ERROR: Error for /home/student/projects/resy-playground/sources/poky/../meta-desire/recipes-desire/python-iot/python3-messageqclient_git.bb:do_package_qa[depends], dependency ${POPULATESYSROOTDEPS} in ' ${POPULATESYSROOTDEPS} virtual/fakeroot-native:do_populate_sysroot' does not contain exactly one ':' character.    
 Task 'depends' should be specified in the form 'packagename:task'                                                                                             
ERROR: Command execution failed: Exited with 1           `

When I remove your layer and check I see this:

`$ bitbake python3-messageqclient -e | grep ^POPULATESYSROOTDEPS=
POPULATESYSROOTDEPS="virtual/x86_64-resy-linux-musl-binutils:do_populate_sysroot"`

So I am not sure what the error tries to tell me and how to fix it.

**Comment by RobertBerger** [comment]
Maybe let me add that I just included meta-sca in bblayers.conf and did not inherit or IHERIT anything yet

**Comment by RobertBerger** [comment]
I guess I'm doing something wrong, since this error seems to exist for core python modules as well

`ERROR: Error for /home/student/projects/resy-playground/sources/poky/../meta-openembedded/meta-python/recipes-devtools/python/python3-configparser_3.5.0.bb:do_package_qa[depends], dependency ${POPULATESYSROOTDEPS} in ' ${POPULATESYSROOTDEPS} virtual/fakeroot-native:do_populate_sysroot' does not contain exactly one ':' character.
 Task 'depends' should be specified in the form 'packagename:task'
ERROR: Command execution failed: Exited with 1
`

**Comment by RobertBerger** [comment]
it looks like this problem is on current master. I checked out some tag and it went away.

**Comment by priv-kweihmann** [comment]
Hi @RobertBerger , the interesting point is that, when I apply your patch from #187 I get the same error. Without it, it's working for me. So I guess a reasonable fix for #187 will solve this one too

**Comment by RobertBerger** [comment]
@priv-kweihmann I use a couple of layers and it's based on some yocto 2.7. If you include a file via require I would add the path (as I suggested) as well anyhow. Strange that it works for you. I would expect it not to work for you since the path is missing.

**Comment by RobertBerger** [comment]
@priv-kweihmann  Wait we are talking about 2 different issues here.

1) exactly one ':' character. 
This goes away for me if I use your tagged version. Otherwise it does not go away for me at all. No matter what I do.

2) the other bug with requires ....bblass not found.

This goes away as soon as I apply the patch as suggested.

**Comment by priv-kweihmann** [comment]
It's a side-effect of overriding staging.bbclass. Somewhere in this construction a task-depend will be set to an invalid value if not all functions from staging.bbclass are present. I recently reworked this part, so in the last tag still the old mechanism is used.

**Comment by RobertBerger** [comment]
BTW it's enough just to add meta-sca to bblayers,conf for this error to appear.
I removed all SCA_ entries in local.conf and still see the problem.

**Comment by priv-kweihmann** [comment]
I know, this is originating from anonymous python function that are execute one each recipe even when there is no reference set on the particular one. The only chance is to remove the layer for now until I found a fix.

**Comment by RobertBerger** [comment]
@priv-kweihmann One workaround is to go back in time, but there are other issues;) So I rather wait for your fix and then hopefully some of the other problems are fixed as well and the others can be fixed on master. Sounds good to me.

**Comment by priv-kweihmann** [comment]
Should be gone with fixed #187
