### ISSUE TITLE
No package 'libffi' found

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#190]
commit 86e3aaaf0c9ced9cc298318120e750f4d581d7e0 (HEAD, tag: v1.13)

```
| No package 'libffi' found
| running build
| running build_py
| running build_ext
| building '_cffi_backend' extension
```

```
ERROR: Task (/home/student/projects/resy-playground/sources/poky/../meta-sca/recipes-python/python-cffi-native/python-cffi-native_1.12.3.bb:do_compile) failed with exit code '1
```
```
sudo apt install libffi-dev
```
seems to fix this problem

One could programmatically ask for host package dependencies, or build what's required ;)

**Comment by priv-kweihmann** [comment]
@RobertBerger thank you very much for your effort. Indeed there was a dependency missing in the recipe.

**Comment by RobertBerger** [comment]
@priv-kweihmann I just started to play with your layer. More to come ;)
Maybe we can also have a chat some time if you have time. Your stuff, assuming I get it work like I want (and you tell me some tricks) would make a nice addition to an Advanced Yocto training and/or some speeches.

**Comment by priv-kweihmann** [comment]
@RobertBerger I would appreciate it, if you spread the word and I do the coding;-).
So I'm definitely open for chatting...

**Comment by RobertBerger** [comment]
@priv-kweihmann Can you please drop me an e-mail? I can't find yours ;) 

robert.berger@reliableembeddedsystems.com

So we can arrange for a chat.
