### ISSUE TITLE
Suppression of warnings/errors doesn't work

### ISSUE THREAD

**Issue by jordanmk** [priv-kweihmann/meta-sca#1995]
**Describe the bug**
I have tried suppressing certain errors, namely cppcheck.cppcheck.wrongPrintfScanfArgNum and flawfinder.flawfinder.strlen, just to test out the suppression, but none of the methods seem to work for me.
What I tried:
- Adding SCA_CPPCHECK_EXTRA_SUPPRESS += "cppcheck.cppcheck.wrongPrintfScanfArgNum" in local.conf
- Adding SCA_CPPCHECK_EXTRA_SUPPRESS += "cppcheck.cppcheck.wrongPrintfScanfArgNum" in my bitbake recipe
- Adding cppcheck.cppcheck.wrongPrintfScanfArgNum in meta-sca/recipes-sca-rules/sca-recipe-cppcheck-rules-native/files/suppress

However, whenever I build the bitbake recipe where the given error appears (I do bitbake -c clean first, just in case), I still get all those errors in the newly created checkstyle and raw files.
Just to see if it's only cppcheck related issue, I tried suppressing one flawfinder error as well, with the same outcome.

I tried looking into how sca-suppress.bbclass works, but I figured you'd be able to see if there's anything wrong much faster.
Maybe I am doing something wrong? 

**Used layer**
- hash of meta-sca layer: 355398bd7e100da68a313264a73bad8ef41bdf7d

**Comment by priv-kweihmann** [comment]
Thank you so much for bringing this up - this is one of those ancient code fragments, which broke somewhere in between - but a fix is on the way (for all of above described use cases)
