### ISSUE TITLE
sca output xml file naming

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#200]
I am looking at `sca/pylint/checkstyle` and see the following for recipes with `${AUTOREV}`:

```
python3-localdatacollector-2.8.3+gitAUTOINC+417c6faf48.xml
python3-localdatacollector-2.8.3+gitAUTOINC+7cc6b27a27.xml
python3-localdatacollector-2.8.3+gitAUTOINC+9cba0db7fb.xml
```
Which is a bit unfortunate, since I use the `prserver` to create packages with this naming:

```
python3-localdatacollector_2.8.3+git5+7cc6b27a27-r0.0_core2-64.ipk
python3-localdatacollector-dev_2.8.3+git5+7cc6b27a27-r0.0_core2-64.ipk
python3-localdatacollector-dbg_2.8.3+git5+7cc6b27a27-r0.0_core2-64.ipk
```
`gitx` i.e. `gitAUTOINC` in the package name counts up automatically on every change (at 5 now) 

Like this I don't need to check which is the latest commit id like `7cc6b27a27` and still know what the latest and greatest version is.

Suggestion 1)
Do you think you could add the number instead of AUTOINC to the .xml naming?

Suggestion 2)
In case one would only like to keep the latest results, could you erase the others?
A variable like there used to be for images `RM_OLD_IMAGE` like `RM_OLD_SCA_OUTPUT` which would wipe e.g the xml stuff before creating new files, hence keeping only the latest info.

**Comment by priv-kweihmann** [comment]
I'll see what I can do...

**Comment by priv-kweihmann** [comment]
Added an option called SCA_CLEAN_BEFORE_EXPORT to enable/disable a feature like suggested in number 2
