### ISSUE TITLE
&lt HTML entity not translated to "<" character in checkstyle.xml

### ISSUE THREAD

**Issue by jordanmk** [priv-kweihmann/meta-sca#2003]
**Describe the bug**
Ok, I am not sure if this is a bug, improvement, or just something that's out of your control. But I will report it anyway, so you are aware of it (if you are not already).
What I noticed is that between the raw.xml and checkstyle.xml format for cppcheck for example, there's a difference, meaning the &apos html element in the raw format is being translated to ' in the checkstyle format, but the &lt element is not converted to "<".
For example, here are the outputs from checkstyle, datamodel and raw for one warning:
**raw** - "Either the condition \&apos;sizeof(payload)**\&lt**;len\&apos; is redundant or the array \&apos;payload[1024]\&apos; is accessed at index 1024, which is out of bounds."
**datamodel** - "Either the condition 'sizeof(payload)**<** len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds."
**checkstyle** - "Either the condition 'sizeof(payload)**\&lt**;len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds."

This checkstyle output means that for example, when parsing the warnings using the warnings-ng Jenkins plugin, you will only get the following as an output "Either the condition 'sizeof(payload)"

**Used layer**
- hash of meta-sca layer - origin/warrior branch

**Comment by priv-kweihmann** [comment]
Interesting, never recognized that so far.
What host side python version are you using? I suspect a bug in there.

**Comment by jordanmk** [comment]
The python version I am using is 3.8.2.

**Comment by priv-kweihmann** [comment]
It seems to be an issue with python ElementTree (although I'm not sure if it is a problem at all on this side).
Running
```python
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
from xml.etree import ElementTree
from xml.dom import minidom

top = Element("checkstyle")
top.set("version", "4.3")

_string = "Either the condition 'sizeof(payload)< len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds."

_fe = SubElement(top, "file", { "name": "foo" })
_fee = SubElement(_fe, "error", {
    "column": "1",
    "line": "1",
    "message": _string,
    "severity": "warning",
    "source": "foo.id"
})

rough_string = ElementTree.tostring(top, 'utf-8')
reparsed = minidom.parseString(rough_string)
_x = reparsed.toprettyxml(indent="  ")
print(_x)
```
produces
```xml
<?xml version="1.0" ?>
<checkstyle version="4.3">
  <file name="foo">
    <error column="1" line="1" message="Either the condition 'sizeof(payload)&lt; len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds." severity="warning" source="foo.id"/>
  </file>
</checkstyle>
```

which looks valid to me - it passes validation checks and can be rendered with various online services - so the problem might be on warning-ng side (do you have any log about what the plugin is actually complaining about?)

**Comment by jordanmk** [comment]
I can't find any logs of warning-ng complaining about it. I can just see the output, being cut at &lt .

**Comment by priv-kweihmann** [comment]
the snippet I posted yesterday, renders just perfect in my jenkins test instance (jenkins 2.250, warning-ng 8.4.0)
![image](https://user-images.githubusercontent.com/46938494/89215810-90a38600-d5c9-11ea-8f13-33d9c639011f.png)

**Comment by priv-kweihmann** [comment]
@jordanmk could be attach a (sanitized) file from your run to this ticket please

**Comment by jordanmk** [comment]
I am currently updating my warnings-ng plugin to 8.4.0 to try it out once more. My jenkins build is 2.235.2 btw, so I might upgrade that as well.
This may sound silly, but which sanitized file are you referring to?

**Comment by priv-kweihmann** [comment]
the checkstyle file from the deploy/images... folder. and by sanitized I mean that you replace any personal information like paths (you could also leave them as they are if you don't mind) in it

**Comment by jordanmk** [comment]
Hope just pasting the file content here should work fine:

\<?xml version="1.0" ?>
\<checkstyle version="4.3">
  \<file name="foo.c">
    \<error column="1" line="264" message="[Package:foobar Tool:cppcheck] Obsolete function 'alloca' called. In C99 and later it is recommended to use a variable length array instead." severity="warning" source="cppcheck.cppcheck.allocaCalled"/>
    \<error column="1" line="123" message="[Package:foobar Tool:cppcheck] Obsolete function 'alloca' called. In C99 and later it is recommended to use a variable length array instead." severity="warning" source="cppcheck.cppcheck.allocaCalled"/>
    \<error column="1" line="326" message="[Package:foobar Tool:cppcheck] The function 'foo_func' is never used." severity="info" source="cppcheck.cppcheck.unusedFunction"/>
  \</file>
  \<file name="bar.c">
    \<error column="1" line="251" message="[Package:foobar Tool:cppcheck] Using strlen() to check if a string is empty is not efficient." severity="info" source="cppcheck.cppcheck.StrlenEmptyString"/>
  \</file>
  \<file name="foobar.c">
    \<error column="1" line="60" message="[Package:foobar Tool:cppcheck] Either the condition 'sizeof(payload)&lt;len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds." severity="warning" source="cppcheck.cppcheck.arrayIndexOutOfBoundsCond"/>
    \<error column="1" line="12" message="[Package:foobar Tool:cppcheck] The function 'bar_func' is never used." severity="info" source="cppcheck.cppcheck.unusedFunction"/>
    \<error column="1" line="55" message="[Package:foobar Tool:cppcheck] Either the condition 'sizeof(payload)&lt;len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds." severity="warning" source="cppcheck.cppcheck.arrayIndexOutOfBoundsCond"/>
  \</file>
  \<file name="one.c">
    \<error column="1" line="174" message="[Package:foobar Tool:cppcheck] %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'size_t {aka unsigned long}'." severity="info" source="cppcheck.cppcheck.invalidPrintfArgType_sint"/>
    \<error column="1" line="126" message="[Package:foobar Tool:cppcheck] %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'size_t {aka unsigned long}'." severity="info" source="cppcheck.cppcheck.invalidPrintfArgType_sint"/>
    \<error column="1" line="64" message="[Package:foobar Tool:cppcheck] %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'size_t {aka unsigned long}'." severity="info" source="cppcheck.cppcheck.invalidPrintfArgType_sint"/>
  \</file>
  \<file name="two.c">
    \<error column="1" line="0" message="[Package:foobar Tool:cppcheck] This file is not analyzed. Cppcheck failed to extract a valid configuration. Use -v for more details." severity="info" source="cppcheck.cppcheck.noValidConfiguration"/>
  \</file>
  \<file name="three.c">
    \<error column="1" line="45" message="[Package:foobar Tool:cppcheck] The scope of the variable 'tvp' can be reduced." severity="info" source="cppcheck.cppcheck.variableScope"/>
    \<error column="1" line="83" message="[Package:foobar Tool:cppcheck] The function 'dnsresolver_gethostbyname' is never used." severity="info" source="cppcheck.cppcheck.unusedFunction"/>
    \<error column="1" line="43" message="[Package:foobar Tool:cppcheck] The scope of the variable 'nfds' can be reduced." severity="info" source="cppcheck.cppcheck.variableScope"/>
  \</file>
\</checkstyle>

**Comment by priv-kweihmann** [comment]
Yeah that interesting it really wasn't translated properly - I will check the whole data flow once more, maybe I missed out on something

**Comment by priv-kweihmann** [comment]
Did you manage to get it working with the updated components?

**Comment by jordanmk** [comment]
I don't think the version of the components make a difference. I went through to some other messages from the same cppcheck warning, and found out the following.
- This ends up with correct output in warnings-ng:
\<error column="1" line="481" message="[Package:foo Tool:cppcheck] Either the condition 'foobar\&lt;0x00' is redundant or the array 'barfoo[2]' is accessed at index -1, which is out of bounds." severity="warning" source="cppcheck.cppcheck.negativeIndex"/>

- This one ends up with the bad output in warnings-ng:
\<error column="1" line="55" message="[Package:bar Tool:cppcheck] Either the condition 'sizeof(payload)\&lt;len' is redundant or the array 'payload[1024]' is accessed at index 1024, which is out of bounds." severity="warning" source="cppcheck.cppcheck.arrayIndexOutOfBoundsCond"/>


The only difference between the two I can notice, is that the non-working one, has a bracket ")" before the &lt symbol. Don't really know if that the cause. Maybe it's something warning-ng is not handling properly.

**Comment by priv-kweihmann** [comment]
I created the issue https://issues.jenkins-ci.org/browse/JENKINS-63388 for you - I hope it can be fixed on the plugin side.
As this isn't a bug here, I'll close this issue now - thanks again for bringing this up.

Feel free to reopen in case you disagree
