### ISSUE TITLE
pylint: Unable to import

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#201]
I get a lot of `pylint Unable to import` errors like this:
```
<error column="1" line="2" message="[Package:python3-localdatacollector Tool:pylint] Unable to import 'daemonize'" severity="error" source="pylint.pylint.import-error"/>
```
Where does pylint look for the imports by default?

With the yocto project we have a per recipe sysroot for quite some time and this would be a good place to look I guess.

Like this we could actually see whether we forgot to install dependencies for certain packages.

**Comment by RobertBerger** [comment]
Further investigation showed, that `RECIPE_SYSROOT` seems to be used for sca. So I just add the dependencies via `DEPENDS` and not just `RDEPENDS` and this seems to fix the problem.

**Comment by priv-kweihmann** [comment]
Yep they search the STAGING_LIBDIR in recipe.
The behavior can be controlled by the variable SCA_PYLINT_LIBATH, currently this is set to 
`${STAGING_LIBDIR}/python${PYTHON_BASEVERSION}/:${STAGING_LIBDIR}/python${PYTHON_BASEVERSION}/site-packages/` for recipes.

With this it's always needed to include dependencies via DEPENDS and not RDEPENDS, because (as far as I know) RDEPENDS doesn't include the sources into the workspace, it's more of a packaging information when later installing into images

**Comment by priv-kweihmann** [comment]
Maybe this should be documented somehow - I'm currently thinking about creating some how-to documents, so if you like you could provide some input or at least some topics to write about

**Comment by RobertBerger** [comment]
In which format do you write the howto? (I am a latex friend, but open to other things as well)

**Comment by RobertBerger** [comment]
... as long as we can keep the ASCII text somewhere under version control

**Comment by priv-kweihmann** [comment]
I'm a big friend of markdown, esp. when using webUI of github, so I would prefer Markdown

**Comment by RobertBerger** [comment]
> With this it's always needed to include dependencies via DEPENDS and not RDEPENDS, because (as far as I know) RDEPENDS doesn't include the sources into the workspace, it's more of a packaging information when later installing into images

Yep RDEPENDS are runtime dependencies for the package manager.

Funny enough, if you use the devtool to generate Python recipes is only uses RDEPENDS ;)

I really like the fact, that I need to add DEPENDS to see what really is included and already found 2 circular dependencies by looking at pylint output. My python developer is already on the case to fix it;)

**Comment by RobertBerger** [comment]
> I'm a big friend of markdown, esp. when using webUI of github, so I would prefer Markdown

I'm happy with Markdown!

**Comment by RobertBerger** [comment]
So I guess you want the doc here on github as some kind of wiki or so.

**Comment by priv-kweihmann** [comment]
Not directly using the wiki feature, I thought more of a subfolder containing a loose collection of files

**Comment by RobertBerger** [comment]
OK fine as well.

BTW this is how I currently use it meta-sca:

https://gitlab.com/meta-layers/meta-resy/blob/master/template-container-x86-64/local.conf.sample#L274

**Comment by priv-kweihmann** [comment]
This will handled by documentation and doesn't require any code changes, therefore this here could be closed

**Comment by RobertBerger** [comment]
Yep the trick is to use `DEPENDS` and not just `RDEPENDS`
