### ISSUE TITLE
force sca checks

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#202]
I am currently playing around and it looks like the sca checks are only ran (I mean I only see new output in the deploy/sca if things are actually built.

Is there a way to force sca runs (for the recipes/image recipes) where I inherited sca?
The idea would be to enable/disable checks and play around with checks on the same sources, where bitbake will not rebuild because stuff is already in sstate.

What causes the sca tests to run and to produce output in deploy/sca?

**Comment by RobertBerger** [comment]
looks like `do_compile` triggers sca.

I did something like this in `local.conf`

```
DISTRO_FEATURES_append = " forcesca"
```

and in each recipe:


```
# in case we have scaforce defined in DISTRO_FEATURES include a file, which enforces compile -> sca
require ${@ bb.utils.contains("DISTRO_FEATURES", "scaforce", "conf/distro/include/sca-force.inc" , "", d)}

```
at the moment `sca-force.inc` only contains:

```
co_compile[nostamp] = "1"
```

This seems to do the trick, but maybe you have a more efficient way of doing it ;)

**Comment by priv-kweihmann** [comment]
Most of the sca-tasks depend on do_compile at recipes and on do_rootfs at images.
Your workaround does provide this somehow.

I agree that a force run would be nice and I consider implementing this somewhere after the next tag, until then your workaround should provide this.

**Comment by priv-kweihmann** [comment]
Added an option called SCA_FORCE_RUN to control the behavior

**Comment by RobertBerger** [comment]
Just pulled the latest and greatest and testing it. 

One more question. is SCA_FORCE_RUN a global variable which applies to everything, or can it be used per recipe/package like SCA_FORCE_RUN_pn-my-package as well?

**Comment by priv-kweihmann** [comment]
Should be working with either include 'SCA_FORCE_RUN = "1"' into recipe or 'SCA_FORCE_RUN_pn-my-package = "1"'... - But I admit I haven't tested it
