### ISSUE TITLE
Add Valgrind as tool

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#234]
Valgrind - An instrumentation framework for building dynamic analysis tools -- Classic, if qmeu-wrapper support is working this is a must

**Comment by RobertBerger** [comment]
How exactly do you want to use valgrind? There is definitely a recipe for it and I have it running on my boards. So I am pretty sure it will also run on qemu. Do you plan to start up a qemu and run it in there?

**Comment by priv-kweihmann** [comment]
Yeah that was my plan. Use qemu-wrapper and run an instance of the tool to be packaged and check for things to be warned about in valgrind output.
Maybe this  could be enhanced by running some test code (or similar) to enhance the coverage

**Comment by RobertBerger** [comment]
This is going to be tricky ;)

1) Ideally you need to configure qemu at least to use the same (cross)-compiler as your real Embedded target for this to be a valid test
2) I saw issues with valgrind not finding issues on ARM and finding them on x86
3.1) sometimes it might be required to run valgrind on the real embedded target
3.2) sometimes it might be enough to run valgrind on some x86 qemu
(same is valid for other tools as well)

**Comment by priv-kweihmann** [comment]
I totally agree that invoke valgrind on ARM is still improvable, but this should be a better than nothing solution (at least in my mind).
As far as I saw it the qemu-native is build with the same flags and from the same sources as the used cross-compiler (if not being hacked by 3rd-party toolchain or whatsoever), so it should give at least some hints about some broken memory things.

I just had this idea, maybe it works maybe not - we'll just see.

**Comment by priv-kweihmann** [comment]
After some thinking about it, i came the conclusion that such a tool would be great in a larger CI/CD pipeline, but is definitely not well placed with static code analysis.
Valgrind should be done as part of dynamic system testing, as it also requires testfiles, sample data a.s.o., to get reasonable results - so it's basically the same a with #504 AFL, which would be great,, but not as part of this layer
