### ISSUE TITLE
gcc tool on a recipe

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#241]
So what I am trying to do now for a couple of days is to get `the gcc tool` to run on a very `simple-hello-world.bb`   recipe which builds a `simple-hello-world.c ` app which creates c compiler warnings and with `the gcc tool` I hope to see them.

I will report my findings later. Just added this not to forget it.

**Comment by RobertBerger** [comment]
One thing is, that it seems to be not enough just to built the recipe, but an image containing the recipe needs to be built.

**Comment by priv-kweihmann** [comment]
There hasn't been any progress for >2 month, so I will close this issue.
If there anything to add, please reopen
