### ISSUE TITLE
sparse

### ISSUE THREAD

**Issue by tprrt** [priv-kweihmann/meta-sca#2462]
**Is your feature request related to a problem? Please describe.**
Sparse, the semantic parser, provides a compiler frontend capable of parsing most of ANSI C as well as many GCC extensions, and a collection of sample compiler backends, including a static analyzer also called sparse. Sparse provides a set of annotations designed to convey semantic information about types, such as what address space pointers point to, or what locks function acquires or releases.

Linus Torvalds started writing Sparse in 2003, initially targeting issues such as mixing pointers to user address space and pointers to kernel address space.

Josh Triplett was Sparse’s first maintainer in 2006. This role was taken over by Christopher Li in 2009 and by Luc Van Oostenryck in late 2018.

**Describe a tool that might help here**
https://sparse.docs.kernel.org/en/latest/index.html
https://git.kernel.org/pub/scm/devel/sparse/sparse.git/tree/Documentation/index.rst

**Comment by priv-kweihmann** [comment]
How about that https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/module/sparse.md? :-)

**Comment by priv-kweihmann** [comment]
@tprrt does the currently available module suit your needs? If so please close the issue, otherwise I would be happy to understand what can be improved

**Comment by tprrt** [comment]
Hello,

Yes, the currently available module suite my needs. Sorry, I hadn't seen that it was already integrated then I am closing this issue.

Best regards,
Thomas
