### ISSUE TITLE
doc: field which indicates if in SCA_AVAILABLE_MODULES= by default

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#249]
doc: additional field which indicates  if in `SCA_AVAILABLE_MODULES=` e.g. `clang` doesn't seem to be there by default

**Comment by priv-kweihmann** [comment]
In the root README you will find
`clang-tidy (c/c++) [clang] disabled by default`

same goes for tlv and oclint.
Or speaking the other way around - what should be exactly documented?

**Comment by RobertBerger** [comment]
I thought about an addition to [this](https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/module/clang.md) kind of files.

**Comment by priv-kweihmann** [comment]
Ahhh now I get it. Yes that would be a fine addition
