### ISSUE TITLE
shellcheck tools doesn't match any files

### ISSUE THREAD

**Issue by fmartinsons** [priv-kweihmann/meta-sca#2540]
**Describe the bug**
Using shellcheck tools, it cannot find any script by its shebang.

**Used layer**
- meta-sca hash: 7bacc64 (tag: vwarrior_1.27.0)
- poky hash: c8c383d958807b991e31d22f612ba2a81a3860a4 (warrior HEAD)
- hashes of additional layer: 4f7be0d252f68d8e8d442a7ed8c6e8a852872d28 of meta-security , a24acf94d48d635eca668ea34598c6e5c857e3f8 of meta-python

**Used configuration**
SCA_ENABLE ?= "0"
SCA_FORCE_RUN ?= "0"
SCA_AUTO_INH_ON_IMAGE ?= "0"
SCA_AUTO_INH_ON_RECIPE ?= "1"
SCA_ENABLE_BESTOF ?= "0"
SCA_ENABLE_IMAGE_SUMMARY ?= "0"
SCA_EXPORT_FINDING_SRC ?= "1"
SCA_WARNING_LEVEL ?= "warning"
SCA_SCOPE_FILTER ?= "security functional"
SCA_AVAILABLE_MODULES ?= "flake8 vulture cppcheck gcc bitbake oelint"
SCA_ENABLED_MODULES_RECIPE ?= ""
SCA_ENABLED_MODULES_IMAGE ?= ""
INHERIT += "sca"

**Additional**
I added traces inside classes/sca-shellcheck-core.bbclass and get_files_by_extention_or_shebang always return empty list (while I got some bash script which doens't end with .sh).
Looking further, I think there is an issue with the regexp construction inside get_files_by_shebang from sca-helper.bbclass, do_sca_shellcheck_core uses a dictionnary for creating regex:
```
for k,v in { "bash": "*./bash", "sh": "*./sh", "ksh": "*./ksh"}.items():
```
which, combined to:
```
pattern = r"^#!\s*{}".format(pattern)
```
will give (for bash)
```
pattern = r"^#!\s**./bash"
```

It is an invalid regex as stated by python re module:
```
>>> pattern = "*./bash"
>>> pattern = r"^#!\s*{}".format(pattern)
>>> cnt="#!/bin/bash\n"
>>> re.match(pattern, cnt)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    re.match(pattern, cnt)
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 6
```

I think the right pattern in sca-shellcheck-core.bbclass should be:
```
for k,v in { "bash": ".*/bash", "sh": ".*/sh", "ksh": ".*/ksh"}.items():
```

After this local correction , I got another error during execution of shellcheck binary:
```
error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

On **warrior** branch, libffi is in version 3.2.1 which provides libffi.so.6 , upgrading manually on libffi 3.3 (recipes found on master branch of openembedded) fix the things and I finally got my results of shellcheck ;)

Is shellcheck binary building on warrior branch of meta-sca can be build towards libffi.so.6 ?

Thanks for the work done for this layer.

**Comment by priv-kweihmann** [comment]
Thanks for reporting this, seems to affect warrior only - meh.
Can you craft a patch for this somehow? I'm currently lacking the resources to setup a full warrior build at my side.
One idea would be to just insert a fake symlink from `libffi.so.6 -> libffi.so.7`

**Comment by priv-kweihmann** [comment]
But I fixed the regex, so this should work now

**Comment by fmartinsons** [comment]
Ok to use my setup for testing, but I don't see where to put this fake symlink inside meta-sca.
Any ideas ?
Thanks for the regex fixes.

By the way, are there any unit test I can run on meta-sca layer to verify that I do not break anything ?

**Comment by priv-kweihmann** [comment]
There is this wrapper script around shellcheck. That sounds like the perfect place for such a check

**Comment by fmartinsons** [comment]
Hmmm, I know this wrapper I'll give it a try in there then.

**Comment by priv-kweihmann** [comment]
And to answer your question with the unit tests, there are some test scripts located in staging branch (e.g. https://github.com/priv-kweihmann/meta-sca/blob/staging/test/buildntest) which you can copy over locally and run from your setup bitbake workspace `/full/path/to/meta-sca/test/buildntest shellcheck`, that should give you the needed results

**Comment by fmartinsons** [comment]
Hello, I do the following in shellcheck-wrapper:
```
if [ ! -e "${STAGING_LIBDIR_NATIVE}/libffi.so.7" -a -e "${STAGING_LIBDIR_NATIVE}/libffi.so.6" ]; then
   ln -s ${STAGING_LIBDIR_NATIVE}/libffi.so.6 ${STAGING_LIBDIR_NATIVE}/libffi.so.7
fi
```

The execution of shellcheck is ok but there is a warning printed in the output (before the XML):
```
recipe-sysroot-native/usr/lib/libffi.so.7: no version information available (required by shellcheck)
<?xml version='1.0' encoding='UTF-8'?>
<checkstyle version='4.3'>
<file name='/home/fmartinsons/TAPOS&#95;build/build&#45;tapos/tmp/work/aimb231&#45;tapos&#45;linux/tapos&#45;upgrade/1.0&#45;r3/set&#95;identity' >
<error line='11' column='28' severity='warning' message='Prefer &#91; p &#93; &#38;&#38; &#91; q &#93; as &#91; p &#45;a q &#93; is not well defined.' source='ShellCheck.SC2166' />
<error line='15' column='8' severity='warning' message='Declare and assign separately to avoid masking return values.' source='ShellCheck.SC2155' />
```

So the XML is not valid and no output are saved in the file sca_raw_shellcheck.xml

**Comment by priv-kweihmann** [comment]
Okay, then I will take your fix (thank btw) and do the rest, if that's okay for you - if you want your "credit" for this change, please attach a patch file to this issue

**Comment by fmartinsons** [comment]
Here is the patch (I renamed it to a *.txt to please github which refuses *.patch)
[0001-Create-a-symlink-for-libffi-version-required-by-shel.txt](https://github.com/priv-kweihmann/meta-sca/files/5376457/0001-Create-a-symlink-for-libffi-version-required-by-shel.txt)

**Comment by fmartinsons** [comment]
Thank you very much, it works like a charm now.

**Comment by priv-kweihmann** [comment]
Perfect, always happy to help :-)
