### ISSUE TITLE
tools from meta-sca in SDK

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#3545]
**add tools from meta-sca to SDK**
Do you think it's possible to add tools from meta-sca to an SDK? (classic and/or extensible SDK?)

**As an example**
cppcheck

**Comment by priv-kweihmann** [comment]
I've been waiting for this for about a year now :-) and yeah I see the use case, but I'm lacking the infrastructure to perform CI for this (github actions are already running on full capacity).
Furthermore I think this would require some major rework of the integration - so I'll leave the issue open but won't promise any progress soon

**Comment by RobertBerger** [comment]
As time permits I will have a look into it. I thought it was easier ;) 
Something like this[1] and BBCLASSEXTEND = "native nativesdk".

[1] https://gitlab.com/meta-layers/meta-resy/-/blob/master/recipes-core/packagegroups/nativesdk-packagegroup-sdk-host.bbappend

**Comment by priv-kweihmann** [comment]
Open points:

- proper packaging of tools for SDK (luckily for native recipes one don't need that)
- convert the glue code logic (bbclass code) to be available in the SDK (that's the bigger one)
  - probably best to create some wrapper (shell?) for it - just to have the same results from SDK and direct build
- and as currently almost all recipes are hardcoded to native, there has to be some refactoring to enable sdk+native but not target build (not sure if that is even possible without heavily using inc-files)
- and the testing ofc
