### ISSUE TITLE
licensecheck: interpretation of results

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#3559]
**What you see in `sca/licensecheck/raw`**

```
cat update-rc.d-0.8.txt

update-rc.d:Using set licenses ['GPLv2+']
update-rc.d:Using detected licenses ['GPL-2.0', 'GPL-2.1', 'GPL-3.0']
update-rc.d:[license] Detected license(s) GPL-2.0 GPL-2.1 GPL-3.0, but set is 'GPLv2+'

```

**What you see in `/update-rc.d/0.8-r0/temp/sca_raw_licensecheck_raw.csv`**
```
 cat ./work/all-resy-linux/update-rc.d/0.8-r0/temp/sca_raw_licensecheck_raw.csv
filename,directory,license,confidence,rootlicenses,md5,sha1,sha256,bytes,byteshuman
update-rc.d,.,GPL-2.0-or-later,100.00%,,12fa23b7d1e5a66e393847119562d7a8,298db791f8d8f32cde4aa497534e41b6abcf398a,66b2c5b07dd870f5ff52476203ad4b40d37734e96e6e803dd4e69cfac34964e5,6365,6.2K
```

**Conclusion**
- Although the tool says it's 100% sure that the license is `GPL-2.0-or-later` the output in `sca/licensecheck/raw` might not immediately give this impression. 
- It might be useful, at least where `lc` is 100% sure, to somehow add this info as well `sca/licensecheck/xxx`?
- I need to investigate a bit more use cases to be able to tell you more, but I guess you get the idea.

As a side note, I guess you feed `LICENSE` into the tool, or how does it pick up `set licenses`?
Here[1] is some yocto to SPDX mapping, but of course I could not find `GPLv2+`, which should be mapped to `GPL-2.0-or-later`, I guess.

Bring in the lawyers ;)

[1] http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/conf/licenses.conf

**Comment by RobertBerger** [comment]
Let me add to this, that looking at various sources and packages, I think `sca_raw_licensecheck_raw.csv` might be very useful for license compliance and, I guess, should also go somewhere into `sca/licensecheck/xxx`.

**Comment by priv-kweihmann** [comment]
> As a side note, I guess you feed LICENSE into the tool, or how does it pick up set licenses
it is `LICENSE_${PN} or LICENSE` so it is package specific and uses the fallback on the global license

internally the `*-or-later` will be expanded to the shown set of licenses, but I agree GPLv2+ is part of that set, so it shouldn't create a finding in this case.

>  I think sca_raw_licensecheck_raw.csv might be -  very useful for license compliance and, I guess, should also go somewhere into sca/licensecheck/xxx

Okay, I'll try to find a way to do that.

BTW the interpretation of the raw input of lc and scancode is done by https://github.com/priv-kweihmann/meta-sca/blob/master/recipes-sca/licensecheck-helper/files/licensecheck - so maybe you want to have a look at this, what can be improved (aka getting rid of those false positives)

**Comment by RobertBerger** [comment]
If you look here[1] it says: "Please note that GPLv3 is not compatible with GPLv2 by itself. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well. When this is the case, you can use the code under GPLv3 to make the desired combination."

What license is the combined work? `GPL-2.0-or-later` or `GPL-3.0`?

We have a compatibility matrix[2].

`GPL-2.0 GPL-2.1 GPL-3.0`

So I guess the `lc` is tool is wrong according to the matrix?

I want to license my code under: `GPL-2.0-or-later`
I want to copy code under: `GPL-3.0`
OK: Combination is under GPLv3 [3]

[1] https://www.gnu.org/licenses/license-list.en.html#GNUGPLv3
[2] https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
[3] "If you have the ability to release the project under GPLv2 or any later version, you can choose to release it under GPLv3 or any later version - and once you do that, you'll be able to incorporate the code released under GPLv3."
