### ISSUE TITLE
Unbuildable dependency for 'core-image-minimal' because of  the packages 'python-ansiblelint-native' and 'python3-pynacl-native'

### ISSUE THREAD

**Issue by ptsarath** [priv-kweihmann/meta-sca#408]
1.Description

Getting unbuildable dependency error while building the image for  core-image-minimal because of the packages  'python-ansiblelint-native', 'python3-pynacl-native' .

2.Used layers

- meta 
- meta-poky
- meta-yocto-bsp
- meta-sca 

3.Used configuration

Configured the local.cong file for cppcheck tool as below  for qemu machine .

# This sets the default machine to be qemux86 if no other machine is selected:
MACHINE ??= "qemux86"
INHERIT += "sca"
SCA_ENABLED_MODULES_RECIPE ?= "\
                            cppcheck \
                             "

4.Executed log 

sarath@ebsy-isar:~/Default-yocto-qemu/poky/new_build$ bitbake core-image-minimal
Loading cache: 100% |###############################################################################################################################################################################| Time: 0:00:00
Loaded 1686 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'python3-pynacl-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-pynacl-native
  python3-pyyaml-native
  python3-py-native
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'python-ansiblelint-native', 'python3-pynacl-native']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
sarath@ebsy-isar:~/Default-yocto-qemu/poky/new_build$

**Comment by priv-kweihmann** [comment]
I've looked into this, without being able to reproduce this with current master so far.
**What version of the meta-sca and the poky layer are you using?**

As I see the weak assignments ("?=") in you local.conf, I guess you have adapted the settings from "c_inflight.md" from the docs folder - I've made some corrections here, but they don't explain the behavior you've getting in the trace.

Is it working (no error trace) when you skip the "SCA_ENABLED_MODULES_RECIPE"-assignment?

**Comment by ptsarath** [comment]
@priv-kweihmann i am able to build without modifying the local.conf file using meta-sca layer  . But but i am getting the above mentioned error after modifying the local.conf  file as  you  mentioned in the configuration examples : "C/C++ code while developing " .

**Comment by priv-kweihmann** [comment]
Interesting - I tried it here locally at it did work, also the thud-pipeline in Travis CI is working.
I recently updated the mentioned document (as there were some tiny mistakes in it).

Could you please try the following block in your local.conf

> INHERIT += "sca"
> SCA_AUTO_INH_ON_IMAGE = "0"
> SCA_AUTO_INH_ON_RECIPE = "1"
> SCA_ENABLED_MODULES_RECIPE = "cppcheck"

esp. the `SCA_AUTO_INH_ON_IMAGE = "0"` is important, as the reported error arises only from the image-part, I guess.

**Comment by priv-kweihmann** [comment]
If that doesn't help please post the output of `bitbake python-ansiblelint-native -e | grep ^DEPENDS` and `bitbake python-ansiblelint-native -e | grep ^PYTHON_PN`, so I can get a clearer view on the things happening

**Comment by ptsarath** [comment]
@priv-kweihmann  thanks for the reply.I modified the local.conf file as you mentioned in your comment , still its failing . Below i am giving you the error log .

ERROR: 407 unbuildable tasks were found.###########################################################                                                                                                 | ETA:  0:00:00
These are usually caused by circular dependencies and any circular dependency chains found will be printed below. Increase the debug level to see a list of unbuildable tasks.

Identifying dependency loops (this may take a short while)...

ERROR: 
Dependency loop #1 found:
  Task /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.15.bb:do_compile (dependent Tasks ['python3-python-magic-native_0.4.15.bb:do_configure'])
  Task /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.15.bb:do_install (dependent Tasks ['python3-python-magic-native_0.4.15.bb:do_compile'])
  Task /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.15.bb:do_populate_sysroot (dependent Tasks ['python3-python-magic-native_0.4.15.bb:do_install'])
  Task /home/sarath/Default-yocto-qemu/poky/meta/recipes-devtools/gcc/gcc-runtime_8.2.bb:do_prepare_recipe_sysroot (dependent Tasks ['gcc-cross_8.2.bb:do_populate_sysroot', 'python3-python-magic-native_0.4.15.bb:do_populate_sysroot', 'automake_1.16.1.bb:do_populate_sysroot', 'libtool-native_2.4.6.bb:do_populate_sysroot', 'gcc-runtime_8.2.bb:do_fetch', 'libgcc_8.2.bb:do_populate_sysroot', 'gnu-config_git.bb:do_populate_sysroot', 'cppcheck-native_1.89.bb:do_populate_sysroot', 'autoconf_2.69.bb:do_populate_sysroot', 'sca-recipe-cppcheck-rules-native_1.0.bb:do_populate_sysroot'])



I tried the command that you mentioned .I am posting the output here below  


sarath@ebsy-isar:~/Default-yocto-qemu/poky/build$ bitbake python-ansiblelint-native -e | grep ^DEPENDS 
ERROR: Nothing PROVIDES 'python3-pynacl-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-pynacl-native
  python3-pyyaml-native
  python3-py-native
ERROR: Nothing PROVIDES 'python3-ansible-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-ansible-native
  python-ansiblelint-native
  python3-nose-native
ERROR: Nothing PROVIDES 'python3-ruamelyaml-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-ruamelyaml-native
  python3-pyyaml-native
  python3-numpy-native
ERROR: Nothing PROVIDES 'python3-paramiko-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-paramiko-native
  python3-mako-native
  python3-pycairo-native
ERROR: Nothing PROVIDES 'python3-bcrypt-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-bcrypt-native
  python3-wrapt-native
  python3-rpm-native
ERROR: Nothing PROVIDES 'python3-enum34-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-enum34-native
  python3-numpy-native
  python-numpy-native
ERROR: Nothing PROVIDES 'python3-cryptography-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-cryptography-native
  python-bcrypt-native
  python-asn1crypto-native
.................
.............

sarath@ebsy-isar:~/Default-yocto-qemu/poky/build$ bitbake python-ansiblelint-native -e | grep ^PYTHON_PN
ERROR: Nothing PROVIDES 'python3-bcrypt-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-bcrypt-native
  python3-wrapt-native
  python3-rpm-native
ERROR: Nothing PROVIDES 'python3-ruamelyaml-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-ruamelyaml-native
  python3-pyyaml-native
  python3-numpy-native
ERROR: Nothing PROVIDES 'python3-setuptools-scm-git-archive-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-setuptools-scm-git-archive-native
  python3-setuptools-scm-native
  python-setuptools-scm-native
ERROR: Nothing PROVIDES 'python3-cryptography-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-cryptography-native
  python-bcrypt-native
  python-asn1crypto-native
ERROR: Nothing PROVIDES 'python3-enum34-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-enum34-native
  python3-numpy-native
  python-numpy-native
ERROR: Nothing PROVIDES 'python3-ansible-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-ansible-native
  python-ansiblelint-native
  python3-nose-native
ERROR: Nothing PROVIDES 'python3-paramiko-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-paramiko-native
  python3-mako-native
  python3-pycairo-native
ERROR: Nothing PROVIDES 'python3-pynacl-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-pynacl-native
  python3-pyyaml-native
  python3-py-native
ERROR: Nothing PROVIDES 'python3-ipaddress-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
  python-ipaddress-native
  python3-iniparse-native
  python3-dparse-native
ERROR: Nothing PROVIDES 'python3-pyasn1-native' (but /home/sarath/Default-yocto-qemu/poky/meta-sca/recipes-sca/python-ansiblelint-native/python-ansiblelint-native_4.1.0.bb DEPENDS on or otherwise requires it). Close matches:
.....................................
.....................................
.....................................

**Comment by priv-kweihmann** [comment]
I guess I got it now - Thank you very much for pointing this one out - Expect fixes later that day
