### ISSUE TITLE
Dependency loop after meta-oe change

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#4110]
**Describe the bug**
Dependency loop after meta-oe change when inheriting sca class globally.

Trimmed down loop = python3-*-native -> python3 -> linux-libc-headers -> glibc -> python3-*-native

This happens as upstream removed fake packaging of native recipes, while http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/distutils3-base.bbclass#n1 is still pulling in python for native recipes.

**Used layer**
- hash of meta-sca layer: master
- poky hash: master 3.2 tag
- meta-openembedded: fd6a007efa7cb45101a66f294af81d9d33bb3fab

**Comment by chbae** [comment]
Thank you for the fix.

> poky hash: master 3.2 tag

This happened in https://git.openembedded.org/openembedded-core/commit/?id=fd6a007efa7cb45101a66f294af81d9d33bb3fab after master 3.2 tag.
