### ISSUE TITLE
duplicate-code-detection-tool

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#4112]
This is a tool that looks interesting:

https://github.com/platisd/duplicate-code-detection-tool

**Comment by priv-kweihmann** [comment]
Uuuuh, yes - thanks, I will have a look

**Comment by priv-kweihmann** [comment]
I think tlv does a better job here, as it points out where the duplicated blocks are (also within a single file) and not just percentage of similarity - thus I don't think that will add much to the mix here
