### ISSUE TITLE
reuse-tool: makes licensing your Free Software projects easier

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#4113]
This is a tool that looks interesting:

https://github.com/fsfe/reuse-tool

One could run `reuse lint` on various projects.

I think it would be most interesting for "your own" code in order to add proper SPDX info.

**Comment by priv-kweihmann** [comment]
On that note: https://github.com/priv-kweihmann/meta-sca/issues/1089
