### ISSUE TITLE
[ERROR] Aborted dependency loops search after 10 matches

### ISSUE THREAD

**Issue by gomme600** [priv-kweihmann/meta-sca#4307]
Hi,
After following the getting started guide here : https://github.com/priv-kweihmann/meta-sca/blob/master/docs/getting_started.md and having the following in /build/conf/local.conf :

SCA_AUTO_INH_ON_IMAGE = "0"
SCA_AUTO_INH_ON_RECIPE = "1"
SCA_AUTO_LICENSE_FILTER = ".*"
SCA_AVAILABLE_MODULES = "ansiblelint flake8 gcc npmaudit"
SCA_BACKTRACK = "0"
SCA_ENABLE_BESTOF = "0"
SCA_ENABLE_IMAGE_SUMMARY = "0"
SCA_EXPORT_FINDING_SRC = "0"
SCA_SPARE_LAYER = ""
SCA_TRACEFILES_MODE = "full"
SCA_VERBOSE_OUTPUT = "1"
SCA_WARNING_LEVEL = "info"
INHERIT += "sca"

I am getting an error: 
...
Dependency loop #11 found:
  Task /home/slucas/meta-sca/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.22.bb:do_compile (dependent Tasks ['python3-python-magic-native_0.4.22.bb:do_configure'])
  Task /home/slucas/meta-sca/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.22.bb:do_install (dependent Tasks ['python3-python-magic-native_0.4.22.bb:do_compile'])
  Task /home/slucas/meta-sca/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.22.bb:do_populate_sysroot (dependent Tasks ['python3-python-magic-native_0.4.22.bb:do_install'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/ncurses/ncurses_6.2.bb:do_prepare_recipe_sysroot (dependent Tasks ['glibc_2.33.bb:do_populate_sysroot', 'autoconf_2.71.bb:do_populate_sysroot', 'pseudo_git.bb:do_populate_sysroot', 'libtool-cross_2.4.6.bb:do_populate_sysroot', 'ncurses_6.2.bb:do_populate_sysroot', 'opkg-utils_0.4.3.bb:do_populate_sysroot', 'automake_1.16.2.bb:do_populate_sysroot', 'python3-python-magic-native_0.4.22.bb:do_populate_sysroot', 'gcc-runtime_10.2.bb:do_populate_sysroot', 'pkgconfig_git.bb:do_populate_sysroot', 'ncurses_6.2.bb:do_fetch', 'libtool-native_2.4.6.bb:do_populate_sysroot', 'gcc-cross_10.2.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/ncurses/ncurses_6.2.bb:do_configure (dependent Tasks ['ncurses_6.2.bb:do_prepare_recipe_sysroot', 'ncurses_6.2.bb:do_patch', 'ncurses_6.2.bb:do_deploy_source_date_epoch'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/ncurses/ncurses_6.2.bb:do_compile (dependent Tasks ['ncurses_6.2.bb:do_configure'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/ncurses/ncurses_6.2.bb:do_install (dependent Tasks ['ncurses_6.2.bb:do_compile', 'pseudo_git.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/ncurses/ncurses_6.2.bb:do_populate_sysroot (dependent Tasks ['ncurses_6.2.bb:do_install', 'binutils-cross_2.36.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/readline/readline_8.1.bb:do_prepare_recipe_sysroot (dependent Tasks ['readline_8.1.bb:do_fetch', 'glibc_2.33.bb:do_populate_sysroot', 'ncurses_6.2.bb:do_populate_sysroot', 'autoconf_2.71.bb:do_populate_sysroot', 'pseudo_git.bb:do_populate_sysroot', 'opkg-utils_0.4.3.bb:do_populate_sysroot', 'automake_1.16.2.bb:do_populate_sysroot', 'gcc-runtime_10.2.bb:do_populate_sysroot', 'python3-python-magic-native_0.4.22.bb:do_populate_sysroot', 'libtool-cross_2.4.6.bb:do_populate_sysroot', 'libtool-native_2.4.6.bb:do_populate_sysroot', 'gcc-cross_10.2.bb:do_populate_sysroot', 'texinfo-dummy-native.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/readline/readline_8.1.bb:do_configure (dependent Tasks ['readline_8.1.bb:do_prepare_recipe_sysroot', 'readline_8.1.bb:do_patch', 'readline_8.1.bb:do_deploy_source_date_epoch'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/readline/readline_8.1.bb:do_compile (dependent Tasks ['readline_8.1.bb:do_configure'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/readline/readline_8.1.bb:do_install (dependent Tasks ['pseudo_git.bb:do_populate_sysroot', 'readline_8.1.bb:do_compile'])
  Task /home/slucas/meta-sca/poky/meta/recipes-core/readline/readline_8.1.bb:do_populate_sysroot (dependent Tasks ['readline_8.1.bb:do_install', 'binutils-cross_2.36.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_prepare_recipe_sysroot (dependent Tasks ['sqlite3_3.34.1.bb:do_populate_sysroot', 'bzip2_1.0.8.bb:do_populate_sysroot', 'gdbm_1.19.bb:do_populate_sysroot', 'opkg-utils_0.4.3.bb:do_populate_sysroot', 'readline_8.1.bb:do_populate_sysroot', 'automake_1.16.2.bb:do_populate_sysroot', 'libxcrypt_4.4.17.bb:do_populate_sysroot', 'python3-python-magic-native_0.4.22.bb:do_populate_sysroot', 'libtool-cross_2.4.6.bb:do_populate_sysroot', 'xz_5.2.5.bb:do_populate_sysroot', 'zlib_1.2.11.bb:do_populate_sysroot', 'libnsl2_git.bb:do_populate_sysroot', 'pkgconfig_git.bb:do_populate_sysroot', 'bzip2_1.0.8.bb:do_populate_sysroot', 'gcc-cross_10.2.bb:do_populate_sysroot', 'openssl_1.1.1i.bb:do_populate_sysroot', 'libffi_3.3.bb:do_populate_sysroot', 'util-linux_2.36.1.bb:do_populate_sysroot', 'gcc-runtime_10.2.bb:do_populate_sysroot', 'libtirpc_1.3.1.bb:do_populate_sysroot', 'libtool-native_2.4.6.bb:do_populate_sysroot', 'glibc_2.33.bb:do_populate_sysroot', 'autoconf_2.71.bb:do_populate_sysroot', 'pseudo_git.bb:do_populate_sysroot', 'python3_3.9.1.bb:do_populate_sysroot', 'python3_3.9.1.bb:do_fetch'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_configure (dependent Tasks ['python3_3.9.1.bb:do_prepare_recipe_sysroot', 'python3_3.9.1.bb:do_deploy_source_date_epoch', 'python3_3.9.1.bb:do_patch'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_compile (dependent Tasks ['python3_3.9.1.bb:do_configure', 'python3_3.9.1.bb:do_configure_ptest_base'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_compile_ptest_base (dependent Tasks ['python3_3.9.1.bb:do_compile'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_install (dependent Tasks ['python3_3.9.1.bb:do_compile', 'python3_3.9.1.bb:do_compile_ptest_base', 'pseudo_git.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_install_ptest_base (dependent Tasks ['python3_3.9.1.bb:do_install'])
  Task /home/slucas/meta-sca/poky/meta/recipes-devtools/python/python3_3.9.1.bb:do_populate_sysroot (dependent Tasks ['python3_3.9.1.bb:do_install_ptest_base', 'python3_3.9.1.bb:do_install', 'binutils-cross_2.36.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.22.bb:do_prepare_recipe_sysroot (dependent Tasks ['python3-python-magic-native_0.4.22.bb:do_fetch', 'python3_3.9.1.bb:do_populate_sysroot', 'python3-setuptools_52.0.0.bb:do_populate_sysroot', 'python3_3.9.1.bb:do_populate_sysroot'])
  Task /home/slucas/meta-sca/meta-sca/recipes-python/python-python-magic-native/python3-python-magic-native_0.4.22.bb:do_configure (dependent Tasks ['python3-python-magic-native_0.4.22.bb:do_prepare_recipe_sysroot', 'python3-python-magic-native_0.4.22.bb:do_deploy_source_date_epoch', 'python3-python-magic-native_0.4.22.bb:do_patch'])

Aborted dependency loops search after 10 matches.

ERROR: Command execution failed: 1

Could anyone help me with this?
Thanks

**Comment by priv-kweihmann** [comment]
Please provide the exact revisions/branches used for poky - I kind of suspect a recent error of poky to cause this

**Comment by gomme600** [comment]
I simply followed the getting started guide. So it was the latest branch from the poky git repository using this command git clone git://git.yoctoproject.org/poky poky.
Here is the output of git show-branch:
xxxxxx@nuc004:~/meta-sca/poky$ git show-branch
[master] yocto-uninative.inc: version 3.0 incorporate seccomp filter workaround

**Comment by priv-kweihmann** [comment]
As I suspected :-) you need to update your master to at least https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=2c0511b2a1dcb9e998528a92a4be0dbb8fe1c3e7 (2021/2/17) to make it work - that has been a bug in poky which was fixed there - without that fix there is no way to enable meta-sca on a poky master via global inherit (for poky master revisions between end of January 2021 - 2021/02/16)

**Comment by priv-kweihmann** [comment]
Bug in poky (https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=2c0511b2a1dcb9e998528a92a4be0dbb8fe1c3e7) causes this - "not our bug" :-)

**Comment by gomme600** [comment]
Ok thanks!

**Comment by gomme600** [comment]
I did this : git checkout c8075ed8f157468849d3199c3671b84a6f08785d
And then this : bitbake core-image-minimal
And I am getting the same error. Have I updated wrong?
This is the description of the commit : https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=c8075ed8f157468849d3199c3671b84a6f08785d

**Comment by gomme600** [comment]
Also, I did the initial git clone yesterday so I don't understand why I would have an out of date master? I'm not an expert on all of this.

**Comment by priv-kweihmann** [comment]
hmmmm, interesting - I will have a look

**Comment by gomme600** [comment]
Thanks
