### ISSUE TITLE
ImportError: The 'enchant' C library was not found.

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#448]
**Describe the bug**
I updated to zeus and make my first experiments. The build breaks both with `meta-sca` `master` and `zeus` branch. See https://pastebin.com/yyaqBvtB

**Used layer**
- hash of meta-sca layer
- poky hash
- hashes of additional layer

see https://pastebin.com/yyaqBvtB

**Used configuration**
- if you're using a non-default configuration for meta-sca-layer, please post the diff here

I can give you remote access to a build. 

**Additional**
Add console printouts if applicable.

I run the build from within a (new) docker container.

```
bitbake-layers show-recipes | grep -A3 python3-pyenchant-native
python3-pyenchant-native:
  meta-sca             2.0.0
```

**Comment by priv-kweihmann** [comment]
Damn it - enchant is installed on my local setup and on the CI nodes by default. Will fix this

**Comment by RobertBerger** [comment]
> Damn it - enchant is installed on my local setup and on the CI nodes by default. Will fix this

Hehe - my new poky container detects those things ;) 
It's derived from crops.
Is there are quick and dirty workaround except for removing your layer?

**Comment by priv-kweihmann** [comment]
There is, disable "msgcheck" module in SCA_AVAILABLE_MODULES
