### ISSUE TITLE
Help wanted: Container support

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#451]
I digged a little into the topic of supporting analysis of container and I have to admit there are a lot of possibilities.
Currently I'm not quite sure what **YOU** (as a user) want to check and in what kind of format.

So please leave comments (or write me a mail) with some use cases, so I can focus on the things that are important for **YOU**.

Also if you already have ideas and/or working code just send some patches/fragments or pull requests.

Thanks

**Comment by RobertBerger** [comment]
I am currently playing around with containers. Currently I build oci containers (via meta-virtualization) and upload them to docker.io via skopeo and the goal is to use kubernetes with those containers.

If you like I can give you access to my stuff and/or my layers plus scripts (once I check everything in).

The nice thing about containers is, that e.g. you can build an x86 container and run it on your PC without hardware.

I would be interested e.g. what capabilities are actually required to run the stuff in the container/pod and what capabilities are actually used to run the pod.

**Comment by RobertBerger** [comment]
This tool[1] looked promising, but it has a bug and there is no support[2] ;)

[1] https://blog.heroku.com/terrier-open-source-identifying-analyzing-containers
[2] https://github.com/heroku/terrier/issues/2

**Comment by priv-kweihmann** [comment]
After careful consideration I don’t think container inspection should or will be part of the layer, as the scope is just too much different from the other tools.
Nevertheless this could be done as part of a new layer (e.g. as an extension to meta-sca), but for this someone needs to step up and do it ;-)
