### ISSUE TITLE
[rocko] cppcheck do_fetch fails because of changing default branch name to `main`

### ISSUE THREAD

**Issue by agrexgh** [priv-kweihmann/meta-sca#4903]
**Describe the bug**
`bitbake cppcheck-native` fails at `do_fetch.
(See #4884 Problem 1 for details).

**Used layer**
- hash of meta-sca layer: `f0521e93e355405a2a54daaaf8d0be5d5bd6d594`
- poky hash : `940da2e688cc6ae3cc3d95842033c3e51bd9fe29`
- hashes of additional layer: -

**Comment by priv-kweihmann** [comment]
Fixed by #4904
