### ISSUE TITLE
staticcheck for go

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#4922]
**Is your feature request related to a problem? Please describe.**

> Staticcheck is a state of the art linter for the Go programming language. Using static analysis, it finds bugs and performance issues, offers simplifications, and enforces style rules.

sounds about right to give it a try (it's also already part of the repository as a dependency on an unrelated tool)

**Describe a tool that might help here**
https://github.com/dominikh/go-tools

**Comment by priv-kweihmann** [comment]
sadly this requires cgo, with no way to turn it off - and native cgo is the most awful thing I could imagine - closing

**Comment by dominikh** [comment]
Staticcheck doesn't require cgo. Unless you're analyzing a project that uses cgo, of course, then Staticcheck will invoke the necessary cgo magic to be able to analyze the code.

**Comment by priv-kweihmann** [comment]
@dominikh okay - I wasn't able to compile it without invoking cgo in openembedded, which is horrible, so decided not to proceed further with this ticket - it's not about your tool at all it's just that go (esp. with cgo) and openembedded in combination are a major pita

**Comment by dominikh** [comment]
Alright. Feel free to ping me if this comes up again in the future :)

**Comment by priv-kweihmann** [comment]
Sure will do
