### ISSUE TITLE
codeclimate output format doesn't match the specification.

### ISSUE THREAD

**Issue by bachp** [priv-kweihmann/meta-sca#5734]
**Describe the bug**
The code climate format is described in https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md

According to https://github.com/priv-kweihmann/meta-sca/issues/726 the codeclimate format implements https://github.com/fulldecent/structured-acceptance-test/blob/master/Stat-Output.md.

As stated in https://github.com/codeclimate/platform/issues/31 and https://github.com/fulldecent/structured-acceptance-test/issues/3 the compatibility between STAT and codeclimate seems to have never been established.

GitLab further defines a [subset](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool ) that is supports. Which seems to be a good fit for meta-sca.

I think the current format should be renamed to structured-acceptance-test and https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool  should be added as codelimate.

**Used layer**
- hash of meta-sca layer: 356a3a801f64fd7eed29fbefcd7f601ab8223025 (dunfell)

**Used configuration**
I enabled `SCA_EXPORT_FORMAT = "codeclimate"`

**Additional**

**References**
- https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool 
- https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md

**Comment by priv-kweihmann** [comment]
@bachp makes sense - as a first step the renaming seems to be reasonable, support for the mentioned "new" format will be added later on - thanks for reporting

**Comment by bachp** [comment]
@priv-kweihmann Thanks for the quick reaction. Should I create a follow up issue to track the progress of adding the new "codeclimate" format?

**Comment by priv-kweihmann** [comment]
@bachp, I already did that https://github.com/priv-kweihmann/meta-sca/issues/5735 :-)
