### ISSUE TITLE
minified version of the layer

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#6116]
Automatically create a minified fork of the layer of the currently supported branches.
- layer does only contain the diffs between tag releases of the branches as single commits
- layer does not offers issues, pull requests a.s.o.
- a README is added pointing back to this layer here
- each commit has a corresponding tag
- commits (and potentially tags) are created automatically by a scheduled task

Optional: skip tag releases < 1.20

**Comment by priv-kweihmann** [comment]
@bachp could that work for your setup?

**Comment by bachp** [comment]
@priv-kweihmann Yes that would work.

**Comment by bachp** [comment]
Related to: https://github.com/priv-kweihmann/meta-sca/issues/6116

**Comment by priv-kweihmann** [comment]
Releases starting from `v1.24.0` are now available at meta-sca-minified

**Comment by bachp** [comment]
Thanks
