### ISSUE TITLE
scancode-toolkit

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#696]
**Is your feature request related to a problem? Please describe.**
scancode-toolkit scans a codebase for license and copyright information, which can be very useful in e.g. the following case

- LICENSE is set to CLOSED although sources aren't closed source
- Multi-licensed sources which should be addressed accordingly
- GPL3 watching (for those who can't use it)
- Copyright blacklisting (for whatever reason)

This might not be the typical tool for SCA, but could be very useful for a lot of use cases...

**Describe a tool that might help here**
https://github.com/nexB/scancode-toolkit

**Comment by priv-kweihmann** [comment]
ATM project doesn't support python 3.7+, which is a blocker right now, but there's wip on that topic - check on it again

**Comment by priv-kweihmann** [comment]
Watch for the following: https://github.com/nexB/scancode-toolkit/pull/1819 & https://github.com/nexB/scancode-toolkit/issues/1817

**Comment by pombredanne** [comment]
@priv-kweihmann you can also track the progress in this board https://github.com/nexB/scancode-toolkit/projects/8

**Comment by pombredanne** [comment]
@Abhishek-Dev09 ping: reminder to ensure you can update  @priv-kweihmann and team when the Python 3.7 and 3.8 is ready

**Comment by Abhishek-Dev09** [comment]
> @Abhishek-Dev09 ping: reminder to ensure you can update @priv-kweihmann and team when the Python 3.7 and 3.8 is ready

@pombredanne OK
