### ISSUE TITLE
Parse error in bitbake build

### ISSUE THREAD

**Issue by ksmanjunath18** [priv-kweihmann/meta-sca#7036]
Hi i added sca layer to my buils, and enabled some configurations.
INHERIT += "sca"
SCA_ENABLE = "1"
SCA_SPARE_LAYER = "core yocto yoctobsp openembedded-layer"
SCA_AUTO_INH_ON_IMAGE = "1"
SCA_AUTO_INH_ON_RECIPE = "1"
SCA_AUTO_LICENSE_FILTER = ".*"
SCA_AVAILABLE_MODULES = "bitbake  gcc"
SCA_ENABLED_MODULES_RECIPE = "bitbake gcc "
SCA_BITBAKE_HARDENING = "\
                        debug_tweaks \
                        insane_skip \
                        security_flags \
                        "
SCA_GCC_HARDENING = "1"

i am getting a error something like this :
ERROR: ParseError at /home/philips/imx-yocto-bsp/sources/meta-sca-minified/recipes-sca/htmlhint-native/htmlhint-native_1.0.bb:18: unparsed line: 'FILES:${PN} += "${datadir}"'
How to resolve this  error,  when i checked into the recipe file configuration was ok.

**Used layer**
- hash of meta-sca layer:**628b7cfeee9e4f83c26ffc4dfc732bd360bba18e**
- poky hash:**58cbdaecf75b0248f96780b6882e8d4f232d038a**

**Comment by priv-kweihmann** [comment]
Supposedly your poky version hasn't been updated to support this https://docs.yoctoproject.org/migration-guides/migration-3.4.html#override-syntax-changes here.
The head commits of poky's master/dunfell/hardknott/gatesgarth should support this, so do the head commits of the respective layer here.

You have two options:
- either stay on hardknott commit d7492a2a477e78275f1e78dc66c5614fd83adcb2 for meta-sca
- or update your poky branch to the latest HEAD

**Comment by ksmanjunath18** [comment]
Thanks For the steps it helped

**Comment by priv-kweihmann** [comment]
@ksmanjunath18 why the reopen? In my understanding this issue can be closed
