### ISSUE TITLE
Build error : with sca inheritted

### ISSUE THREAD

**Issue by Manjunath1207** [priv-kweihmann/meta-sca#7414]
Hi ,
I have setup a build environment i had raised an issue earlier #[link](https://github.com/priv-kweihmann/meta-sca/issues/7036)
I tried the suggestion for the same the parse error is not there but after that i am getting error in meta layers  one of the recipe as 
below:

> ERROR: Nothing PROVIDES 'sca-recipe-yamllint-rules-nativelibical-native' (but /home/xxxx/imx-yocto-bsp/sources/poky/meta/recipes-support/libical/libical_3.0.9.bb DEPENDS on
>   sca-recipe-pylint-rules-native
>   sca-recipe-xmllint-rules-native
>   sca-recipe-yamllint-rules-native

I tried to resolve this issue which i was not able to other details of build are in my previous issue which I had posted  ([issue](https://github.com/priv-kweihmann/meta-sca/issues/7036)).
do you have any idea what is this abut.

**Comment by priv-kweihmann** [comment]
That actually looks like there is a space missing in one of the appends. So likely something like 
```
a = "foo"
a:append = "bar"
```
while it has to be 
```
a = "foo"
a:append = " bar"
```

maybe you could double check with the help of `bitbake libical -e`

**Comment by Manjunath1207** [comment]
Hi , Thanks for the response,
But i see this file in sca layer :**classes/sca-yamllint-recipe.bbclass**
whose contents had something like:
```

## SPDX-License-Identifier: BSD-2-Clause
## Copyright (c) 2019, Konrad Weihmann

inherit sca-helper
inherit sca-global
inherit sca-yamllint-core
inherit sca-tracefiles

do_sca_yamllint_core[doc] = "Lint yaml files"
do_sca_yamllint_core_report[doc] = "Report findings from do_sca_yamllint_core"
addtask do_sca_yamllint_core after do_compile before do_sca_tracefiles
addtask do_sca_yamllint_core_report after do_sca_tracefiles before do_sca_deploy

DEPENDS += "sca-recipe-yamllint-rules-native"
~
~
~
~
is it because of this dependency 

```

**Comment by priv-kweihmann** [comment]
`DEPENDS:append:class-target = "libical-native"` from the libical recipe is just wrong...
it has to be DEPENDS:append:class-target = " libical-native"` - I will create a patch for that and sent it upstream

**Comment by priv-kweihmann** [comment]
Patches are out on the mailing list - in case you want to cherry-pick them into your local poky layer

**Comment by priv-kweihmann** [comment]
http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=2be47ef344efbdc278956e3d83f92977d0c8e617 does provide the needed fix for master branch - please cherry-pick it manually in case you need it for a different branch
