### ISSUE TITLE
How to use go-gen script to generate Go Bitbake recipes?

### ISSUE THREAD

**Issue by jetm** [priv-kweihmann/meta-sca#7499]
**Describe the bug**
I want to generate Bitbake recipes for oasdiff Go module. But I found this error:
```
$ scripts/go-gen oasdiff
Traceback (most recent call last):
  File "scripts/go-gen", line 542, in <module>
    main()
  File "scripts/go-gen", line 532, in main
    args = create_parser()
  File "scripts/go-gen", line 63, in create_parser
    action="extend", nargs="*", help="Ignore licenses from these pattern")
  File "/usr/lib/python3.7/argparse.py", line 1367, in add_argument
    raise ValueError('unknown action "%s"' % (action_class,))
ValueError: unknown action "extend"
``` 
I am not doing any setup. Just calling directly `go-gen` script from staging branch.
I read https://bitbakesoda.blogspot.com/2021/04/making-go-not-no-go.html. And, I had the impression just calling the script would be enough.

**Comment by jetm** [comment]
Removing the License warning was done with this:
```diff
diff --git a/scripts/go-gen-errata.json b/scripts/go-gen-errata.json
index 486a6f5a5..cdfbb7f79 100644
--- a/scripts/go-gen-errata.json
+++ b/scripts/go-gen-errata.json
@@ -592,5 +592,16 @@
         "extramods": [
             "sourcegraph.com/sourcegraph/appdash-data"
         ]
+    },
+    "github.com/tufin/oasdiff": {
+        "licenses": [
+            {
+                "file": "LICENSE",
+                "spdx": "Apachev2"
+            }
+        ],
+        "striplevel": 1,
+        "url": "https://github.com/Tufin/oasdiff/archive/refs/tags/v%VERSION%.zip",
+        "version": "1.0.6"
     }
-}
\ No newline at end of file
+}
```
Thank you for the suggestion.

Are you planning on merging go-gen to master? Thinking of adding a README with these findings.

**Comment by priv-kweihmann** [comment]
Btw currently the tool is only generating native recipes, so it might be useful to add some support for target and nativesdk as well - here as well PRs welcome :)

**Comment by priv-kweihmann** [comment]
Add some documentation to staging branch - I hope that will do it, just let me know if that's enough
