### ISSUE TITLE
Exception: FileNotFoundError: [Errno 2] No such file or directory: work/yocto-tmp/image/work/congatec_tca5_64-poky-linux/plcs-image/1.0-r0/work_upc/recipe-sysroot-native/etc/apt/apt.conf.sample'

### ISSUE THREAD

**Issue by MehdiKarimi786** [priv-kweihmann/meta-sca#850]
**Describe the bug**
**Describe the bug**
When I inherit sca in my recipe, and enable sca on image, I received the following issue:
The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_sca_reconbf(d)
     0003:
File: 'meta-sca/classes/sca-reconbf-image.bbclass', lineno: 86, function: do_sca_reconbf
     0082:    d.setVar("SCA_RAW_RESULT_FILE", result_raw_file)
     0083:
     0084:    _args = ["/bin/sh", "-c", "mkdir -p /tmp;python3 -m reconbf -c {} -rt json -dm all -rf /tmp/reconbf.result >/dev/null 2>&1;cat /tmp/reconbf.result".format(d.getVar("SCA_RECONBF_CONFIG"))]
     0085:
 *** 0086:    cmd_output = sca_crossemu(d, _args, ["reconbf"], "reconbf", ";")
     0087:
     0088:    if not isinstance(cmd_output, str):
     0089:        cmd_output = cmd_output.decode("utf-8")
     0090:    with open(result_raw_file, "w") as o:
File: 'meta-sca/classes/sca-crossemu.bbclass', lineno: 14, function: sca_crossemu
     0010:    import subprocess
     0011:    import os
     0012:
     0013:    if not nocreateroot:
 *** 0014:        _target_path = do_sca_create_crossemu_img(d, toolname, addpkgs, postcmd)
     0015:    else:
     0016:        _target_path = os.path.join(d.getVar("WORKDIR"), "rootfs_{}".format(toolname))
     0017:
     0018:    cmd_output = ""
File: 'meta-sca/classes/sca-crossemu-image.bbclass', lineno: 76, function: do_sca_create_crossemu_img
     0072:    create_manifest(dc)
     0073:
     0074:    # generate rootfs
     0075:    dc.setVarFlag('REPRODUCIBLE_TIMESTAMP_ROOTFS', 'export', '1')
 *** 0076:    create_rootfs(dc, progress_reporter=None, logcatcher=logcatcher)
     0077:
     0078:    execute_pre_post_process(dc, postcmd)
     0079:
     0080:    _qemu = "{}-static".format(qemu_target_binary(d))
File: 'poky/meta/lib/oe/rootfs.py', lineno: 980, function: create_rootfs
     0976:        RpmRootfs(d, manifest_dir, progress_reporter, logcatcher).create()
     0977:    elif img_type == "ipk":
     0978:        OpkgRootfs(d, manifest_dir, progress_reporter, logcatcher).create()
     0979:    elif img_type == "deb":
 *** 0980:        DpkgRootfs(d, manifest_dir, progress_reporter, logcatcher).create()
     0981:
     0982:    os.environ.clear()
     0983:    os.environ.update(env_bkp)
     0984:
File: 'poky/meta/lib/oe/rootfs.py', lineno: 620, function: __init__
     0616:        bb.utils.remove(self.d.getVar('MULTILIB_TEMP_ROOTFS'), True)
     0617:        self.manifest = DpkgManifest(d, manifest_dir)
     0618:        self.pm = DpkgPM(d, d.getVar('IMAGE_ROOTFS'),
     0619:                         d.getVar('PACKAGE_ARCHS'),
 *** 0620:                         d.getVar('DPKG_ARCH'))
     0621:
     0622:
     0623:    def _create(self):
     0624:        pkgs_to_install = self.manifest.parse_initial_manifest()
File: 'poky/meta/lib/oe/package_manager.py', lineno: 1522, function: __init__
     1518:        self.all_arch_list = archs.split()
     1519:        all_mlb_pkg_arch_list = (self.d.getVar('ALL_MULTILIB_PACKAGE_ARCHS') or "").split()
     1520:        self.all_arch_list.extend(arch for arch in all_mlb_pkg_arch_list if arch not in self.all_arch_list)
     1521:
 *** 1522:        self._create_configs(archs, base_archs)
     1523:
     1524:        self.indexer = DpkgIndexer(self.d, self.deploy_dir)
     1525:
     1526:    def mark_packages(self, status_tag, packages=None):
File: 'poky/meta/lib/oe/package_manager.py', lineno: 1757, function: _create_configs
     1753:            if variant_arch not in base_arch_list:
     1754:                base_arch_list.append(variant_arch)
     1755:
     1756:        with open(self.apt_conf_file, "w+") as apt_conf:
 *** 1757:            with open(self.d.expand("${STAGING_ETCDIR_NATIVE}/apt/apt.conf.sample")) as apt_conf_sample:
     1758:                for line in apt_conf_sample.read().split("\n"):
     1759:                    match_arch = re.match(r"  Architecture \".*\";$", line)
     1760:                    architectures = ""
     1761:                    if match_arch:
Exception: FileNotFoundError: [Errno 2] No such file or directory: work/yocto-tmp/image/work/congatec_tca5_64-poky-linux/plcs-image/1.0-r0/work_upc/recipe-sysroot-native/etc/apt/apt.conf.sample'

I checked the directory that is used as WORKDIR by sca-crossemu-image on line 45:
dc.setVar("WORKDIR", os.path.join(d.getVar("WORKDIR"), "work_{}".format(tool)))
the apt.conf.sample does not exist there. even recipe-sysroot-native directory does not exist inside work_upc. Actually apt.conf.sample is located in work/yocto-tmp/image/work/congatec_tca5_64-poky-linux/plcs-image/1.0-r0/recipe-sysroot-native.

So if I remove line #45, then this issue will not happen anymore.

**Used layer**
- hash of meta-sca layer: 47e7f41b12f229b2282bc0040f6a730a68954388
- poky hash: 4edf4eb9cc86fbd4b51240fae527c1b97a7ace74
- hashes of additional layer:
meta-yocto-bsp       = "HEAD:4edf4eb9cc86fbd4b51240fae527c1b97a7ace74"
meta-oe
meta-webserver
meta-filesystems
meta-networking
meta-python          = "HEAD:a24acf94d48d635eca668ea34598c6e5c857e3f8"
meta-intel           = "HEAD:29ee4852a05931dcf856670d9d8a3c3077a40fe8"
meta-congatec-x86    = "HEAD:abcdb4e29cc272c3f7dcfe3a98ed36e86648031d"
meta-updater         = "HEAD:5163ff50bb45903ca31b5b19220ad9ddf54ee0c1"
meta-java            = "HEAD:d0a9fe08be6e1c2e7f7afc79abc292d3bffeb9fe"
meta-gplv2           = "HEAD:d5d9fc9a4bbd365d6cd6fe4d6a8558f7115c17da"
meta-aaas-binary     = "HEAD:ce589db8bf18e630fc9533fc97c9bda62fce2da4"
yocto                = "HEAD:759ee3aa886fde7d38e957e42960bb16c84ecf39"
meta-sca             = "HEAD:47e7f41b12f229b2282bc0040f6a730a68954388"

**Used configuration**
- if you're using a non-default configuration for meta-sca-layer, please post the diff here
SCA_ENABLE = "1"
SCA_EXPORT_FORMAT = "checkstyle"
SCA_WARNING_LEVEL = "info"
SCA_VERBOSE_OUTPUT = "0"
SCA_SCOPE_FILTER = "security functional style"

SCA_GCC_HARDENING = "0"
SCA_ENABLE_BESTOF = "0"

SCA_AUTO_INH_ON_RECIPE = "0"
SCA_ENABLE_IMAGE_SUMMARY = "1"
SCA_AUTO_INH_ON_IMAGE = "1"

SCA_FORCE_RUN = "1"
SCA_CLEAN_BEFORE_EXPORT = "1"

**Additional**
Add console printouts if applicable.

**Comment by priv-kweihmann** [comment]
Interesting, I'll have look into that

**Comment by priv-kweihmann** [comment]
@MehdiKarimi786  I just had a look at the code from poky - I looks like you're using DPKG as packaging format (I honestly tested it only with opkg and rpm). But I guess it would be somehow easy to fix - seems to be a path resolving issue.
Would you have some time to test that? - if so I would branch out a fix from latest warrior branch later that day

**Comment by priv-kweihmann** [comment]
I just pushed a test branch at `crossqemu_workdir_fix`, which works for me (check on the paths).
Could you please confirm that this works for you as well - if so, I will include the patch into all branches - Thanks
