### ISSUE TITLE
ERROR: ParseError at /pamela/sources/meta-sca/dynamic-layers/meta-oe/php_%.bbappend:1: unparsed line: 'PACKAGECONFIG:class-native = "mbstring openssl zip"'

### ISSUE THREAD

**Issue by gomme600** [priv-kweihmann/meta-sca#8555]
Hello,

I'm getting a weird error using meta sca : ERROR: ParseError at /pamela/sources/meta-sca/dynamic-layers/meta-oe/php_%.bbappend:1: unparsed line: 'PACKAGECONFIG:class-native = "mbstring openssl zip"'

It looks like the error is with metasca itsself but I'm not too sure how to proceed.

Thanks for any help!

**Comment by priv-kweihmann** [comment]
What is the exact trailing error message?
What other layers and what versions are you using?

**Comment by priv-kweihmann** [comment]
If I have to take a wild guess then I'd say you're using the meta-sca layer with a poky layer that doesn't support the new override syntax.
Following versions of poky do work with there corresponding branches of meta-sca
- master -> master
- honister -> honister
- hardknott -> hardknott
- dunfell -> dunfell

even
- gatesgarth -> gatesgarth
would work.

All other combination are not going to work properly

**Comment by gomme600** [comment]
There is no trailing error at least in the log I have.

This is my configuration in local.conf :

        SCA_AUTO_INH_ON_IMAGE = "0"
        SCA_AUTO_INH_ON_RECIPE = "1"
        SCA_AUTO_LICENSE_FILTER = ".*"
        SCA_AVAILABLE_MODULES = "oelint"
        SCA_BACKTRACK = "0"
        SCA_ENABLE_BESTOF = "0"
        SCA_ENABLE_IMAGE_SUMMARY = "0"
        SCA_EXPORT_FINDING_SRC = "0"
        SCA_SPARE_LAYER = ""
        SCA_TRACEFILES_MODE = "full"
        SCA_VERBOSE_OUTPUT = "1"
        SCA_WARNING_LEVEL = "info"
        INHERIT += "sca"

I'm using dunfell for the build.

**Comment by gomme600** [comment]
I'm running the build in a CROPS container and using the meta-sca-minified repo in a GitLab-CI environnement. Meta sca worked when I tried on warrior last year.

**Comment by priv-kweihmann** [comment]
poky dunfell-23.0.13 (released some weeks ago) should support the syntax and therefore don't crash at parsing.
If you can't update your dunfell release I would suggest to stay on https://github.com/priv-kweihmann/meta-sca-minified/releases/tag/vdunfell_1.35.0 as this is the last version that doesn't require latest greatest dunfell

**Comment by gomme600** [comment]
Thanks, I'll try that !

**Comment by gomme600** [comment]
It's working now ! Thanks for the fast support !
