### ISSUE TITLE
Pylint supression doesn't seem to work

### ISSUE THREAD

**Issue by RaGrCobham** [priv-kweihmann/meta-sca#8980]
**Describe the bug**
I can't suppress pylint errors at all

**Used layer**
- meta-sca-minified = "HEAD: 7e4333dea87ebfcc4734fca1b6ad51a48972c3b9"
- meta-poky            = "HEAD:c40ac16d79026169639f47be76a3f7b9d8b5178e"
- meta-freescale       = "HEAD:31a9d22895598a77e8320ca77787a81c81294697"

**Used configuration**
- Added suppress files to:
.../meta-layer/recipes-sca-rules/sca-recipe-pylint-rules-native/files/suppress
.../meta-layer/recipes-sca-rules/sca-image-pylint-rules-native/files/suppress

with "pylint.pylint.*" as content

**Additional**
I made sure to delete the output every time before building.

**Comment by priv-kweihmann** [comment]
Can't reproduce it locally.
What recipe did you tried that on?
Could you kindly check the content of `tmp/deploy/images/<arch>/sca/pylint/<recipe>.dm` - does it contain?

Could you try `bitbake <recipe> -c cleansstate && bitbake <recipe>` and see if that changes the output (background is that sca modules are using sstate caches so deleting the output is mostly not enough)

**Comment by RaGrCobham** [comment]
Forgot to add, we did use the wizard output and added some stuff:

```
# Relative from build folder
SCA_EXPORT_DIR = "${TOPDIR}/../Result/sca"
SCA_CLEAN_BEFORE_EXPORT = "1"
SCA_AUTO_INH_ON_IMAGE = "1"
SCA_AUTO_INH_ON_RECIPE = "1"

SCA_AUTO_LICENSE_FILTER = ".*"
SCA_AVAILABLE_MODULES = "pylint clang"
SCA_ENABLED_MODULES_RECIPE = "pylint clang"
SCA_ENABLED_MODULES_IMAGE = "bitbake oelint"
SCA_BACKTRACK = "1"
SCA_ENABLE_BESTOF = ""
SCA_ENABLE_IMAGE_SUMMARY = "0"
SCA_EXPORT_FINDING_SRC = "1"
SCA_SPARE_LAYER = "oe core yocto yoctobsp"


PYTHON_INC_DIR 		= "${STAGING_INCDIR}/${PYTHON_DIR}"
PYTHON_LIB_DIR 		= "${STAGING_BASELIBDIR}/${PYTHON_DIR}"
PYTHON_SITEPACK_DIR = "${RECIPE_SYSROOT}/${PYTHON_SITEPACKAGES_DIR}"

# Used for deployed libraries
IMAGE_ROOTFS_LIB_DIR = "${IMAGE_ROOTFS}/usr/lib/"

# Has to be space separated. The '+=' operator inserts a space. The '.=' doesn't
SCA_CLANG_ADD_INCLUDES += "${STAGING_INCDIR} ${STAGING_INCDIR_NATIVE} ${PYTHON_INC_DIR}"
					  
SCA_PYLINT_LIBATH .= "${STAGING_BASELIBDIR}/:${PYTHON_LIB_DIR}/:${PYTHON_SITEPACK_DIR}/:${IMAGE_ROOTFS_LIB_DIR}"

# Regex is used to match the path of the layers because they are located outside poky
# so using the SCA_SPARE_LAYER variable doesn't work for them
SCA_SPARE_DIRS += "(.*meta-openembedded.*) \
				  (.*meta-networking.*) \
				  (.*meta-freescale.*) \
				  (.*meta-clang.*) \
				  (.*meta-sca.*) \
				  (.*hiredis.*) \
				  (.*gtest.*) \
				  (.*python3.9.*) \
				 "

SCA_SPARE_IGNORE_BBAPPEND = "1"

SCA_TRACEFILES_MODE = ""
SCA_VERBOSE_OUTPUT = "1"
SCA_WARNING_LEVEL = "warning"
SCA_SCOPE_FILTER = "security functional"
SCA_STD_PYTHON_INTERPRETER = "python3"

# This didn't do anything either
SCA_PYLINT_EXTRA_SUPPRESS += "pylint.pylint.*
```"


All the dm files are empty and always were. Also the SCA_SPARE_DIRS doesn't want to ignore gtest include path for some reason...

**Comment by RaGrCobham** [comment]
We have the build running in Jenkins and it build from scratch, from a fresh Git pull every time. And the issue is the same.

**Comment by priv-kweihmann** [comment]
```
SCA_SPARE_DIRS += "(.*meta-openembedded.*) \
				  (.*meta-networking.*) \
				  (.*meta-freescale.*) \
				  (.*meta-clang.*) \
				  (.*meta-sca.*) \
				  (.*hiredis.*) \
				  (.*gtest.*) \
				  (.*python3.9.*) \
				 "
```

Doens't look right to me - this variable is used to determine the **recipes** to be skipped not paths within a recipe.
From my point of view this should be something like

```
# this will ignore the layers by their internal name
# no matter where they are stored
SCA_SPARE_LAYER += "\
    clang-layer \
    openembedded-layer \
    freescale-layer \
    qt5-layer \
    meta-sca \
"

# this will automatically suppress any finding
# where the path contains a matching pattern
#
# the last item will suppress all pylint items found
# no matter in what recipe or path
SCA_SUPPRESS_LOCALS = " \
    .*gtest.*,*,*,* \
    .*python3.9.*,*,*,* \
    .*hiredis.*,*,*,* \
    .*,pylint.pylint.*,*,* \
"
```

**Comment by RaGrCobham** [comment]
```
# this will ignore the layers by their internal name
# no matter where they are stored
SCA_SPARE_LAYER += "\
    clang-layer \
    openembedded-layer \
    freescale-layer \
    qt5-layer \
    meta-sca \
"
```


As soon as I start building, it starts listing all the recipes in meta-openembedded. Like the comment said, the layers are located in the same directory as poky, not inside it. I assume if it were inside, it would work.


```
SCA_SUPPRESS_LOCALS = " \
    .*,pylint.pylint.W1202.*,*,* \
    .*,pylint.pylint.C0103.*,*,* \
    .*,pylint.pylint.C0301.*,*,* \"

or

SCA_SUPPRESS_LOCALS = " \
    .*,pylint.pylint.W1202,*,* \
    .*,pylint.pylint.C0103,*,* \
    .*,pylint.pylint.C0301,*,* \"

```

These aren't being suppressed either

**Comment by priv-kweihmann** [comment]
Hmmmm, could you please check if any of the settings like `SCA_PYLINT_EXTRA_SUPPRESS` or `SCA_SUPPRESS_LOCALS` are effective in any random recipe that should be checked.
Like what is the output of `bitbake <recipe> -e | grep ^SCA_SUPPRESS_LOCALS`?

As of now I haven't found any code path that would skip effective suppression settings

**Comment by RaGrCobham** [comment]
` bitbake <recipe> -e | grep ^SCA_SUPPRESS_LOCALS?` shows exactly what is being put there.

I tried `SCA_SUPPRESS_LOCALS="pylint.pylint*", SCA_SUPPRESS_LOCALS="pylint.pylint.C3025", SCA_SUPPRESS_LOCALS="pylint.pylint.C*".` None of them suppress

These don't work either inside a specific recipe:
`SCA_PYLINT_EXTRA_SUPPRESS += "pylint.pylint.C0325"
SCA_SUPPRESS_LOCALS = "database.py,pylint.pylint.C0303,0-100,*"`

It seems to me that the errors would be detected regardless, but it's the reporting step that filters the suppressed ones. Is that how it works?

**Comment by priv-kweihmann** [comment]
Yes that is how it works - the raw data remains untouched.
So is it the case that you are looking at them all the time?

**Comment by priv-kweihmann** [comment]
Well they are usually stored in different folders where one would find the exported raw data.
https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/results.md explains the folder structure and
https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/output_formats.md the possible export formats.

For example in my reference build I find all pylint findings under
```
tmp/deploy/images/qemux86-64/sca/pylint/
├── checkstyle
│   └── python3-git-3.1.24.xml
├── datamodel
│   └── python3-git-3.1.24.dm
└── raw
    └── python3-git-3.1.24.txt
```
raw is the unfiltered output of pylint, datamodel is the filtered and parsed internal storage and checkstyle folder contains the results to be used by external tools (in this case here in checkstyle format)

**Comment by priv-kweihmann** [comment]
and if you're not getting data from in any of these files I would suggest to have a look at `SCA_SCOPE_FILTER` and/or `SCA_WARNING_LEVEL`.
I'd say most of the findings of pylint are considered of `style` issues with `info` level severity.
Both of them you disabled in your used configuration

**Comment by priv-kweihmann** [comment]
https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/module/pylint.md explains which what pylint IDs are considered for which scope and https://github.com/priv-kweihmann/meta-sca/blob/3fc1148462311ba5cb4069eed93c66843f3492af/classes/sca-pylint-core.bbclass#L22 shows how the severity is mapped to a certain level.
If you want to changed the severity level of a specific pylint ID you might want to try https://github.com/priv-kweihmann/meta-sca/blob/master/docs/conf/sevtransform.md

**Comment by RaGrCobham** [comment]
This is interesting. The clang tool does fill some datamodels but not pylint.

I changed the WARNING_LEVEL to info and included everything in SCOPE_FILTER but pylint still empty...

**Comment by RaGrCobham** [comment]
And relative to the last Jenkins build, the clang data model increased when I expanded the scope and level.

**Comment by priv-kweihmann** [comment]
But the datamodel files were created?

**Comment by RaGrCobham** [comment]
To clarify:

clang has both datamodel and checkstyle files that have data with the found errors

pylint also has both but they're default. Checkstyle files  just have `<checkstyle version="4.3"/>` inside

**Comment by RaGrCobham** [comment]
Ok... I figured it out. It was having `(.*python3.9.*)` in SCA_SPARE_DIRS...

I'm still confused how SPARE_LAYER is better than SPARE_DIRS? With spare layer, should static analysis be done at all, or is it supposed to just filter what's found in those layers.

**Comment by priv-kweihmann** [comment]
Both of them just determine if any of the configured SCA modules should be injected into the current recipe.
`SCA_SPARE_LAYER` is a collection of layer names matched against `BBFILE_COLLECTIONS` and then using the corresponding `BBFILE_PATTERN_<layername>` (the same pattern that you would find as `BBFILES` in every `layer.conf`) to exclude __recipes__.
Meaning that all files from that layer that will be used by the bitbake build are not being injected with any sca tasks.
(You can confirm this behavior by looking at the different output of `bitbake <recipe> -c listtasks` for a recipe from a spared layer and one that is not).
`SCA_SPARE_DIRS` is the same but based purely on path assumptions, which makes it more flexible but also more error prone.

For me the main advantage of using the first option is that the directory and path of the layer does not need to be known.
So it doesn't matter if the poky/meta layer for instance sits at /some/path/layer/my/git/checkout or at /some/path/layer/poky/meta or any other path, as the path if determined by bitbake:
While using the DIRS options requires to know at least some unique part of the path of the layer.
Additionally the DIRS option would also filter out subpaths of the layer like recipes-core/abc/meta-openembedded-pkggroup.bb if DIRS would contain `.*meta-openembedded.*` - and I guess that is not desired in most setups.

Just to emphasize it once more both options just work on recipes and configure if any SCA tasks are to be run or none at all (there is no way it would only activate a partial subset of the configure SCA tasks)

My takeaway of our discussion is that I will take a look into what's happening with a directory setup like yours and why it's not producing the effect like I would expect it.
Could you kindly provide a tree-view of your poky + the layers below that directory so I can reproduce it here locally - THX.

**Comment by RaGrCobham** [comment]
Ok, I checked BBFILE_COLLECTIONS and added the relevant layers as:

`SCA_SPARE_LAYER += "\
    core \
    yocto \
    freescale-layer \
    openembedded-layer \
    meta-python \
    networking-layer \
    meta-sca \
    clang-layer \
"`

None of them  appeared when bitbake was listing which recipes to use with SCA. So that's good.

Is there a way to suppress errors containing a specific string in the error message? As a specific example, pylint complains about missing names in a shared object (.so) that's built for a different architecture than the machine running the analysis and says `[Package:dhcp Tool:pylint] No name 'dhcpser' in module 'libdhcp'`

We could suppress the error allt ogether, but I'd prefer just to suppress those specific libraries.

**Comment by priv-kweihmann** [comment]
Unfortunately as of now only the whole suppression system works with IDs only - but to me that sounds like a good enhancement.
if those items do have a unique ID you can make it work with

```
SCA_SUPPRESS_LOCALS = " \
    .*,pylint.pylint.<id>,*,* \
"
```
