### ISSUE TITLE
Remove no-native-pycache.bbclass

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#9180]
Likely upstream poky will finally address that, so we can safely remove the class code from the master branch

**Comment by SJLC** [comment]
This is in master now
https://git.yoctoproject.org/poky/commit/?id=ed2ba22d108f79cc0f9e9aa555862158f61793ea

I don't think I've ever seen that weird symptom you mentioned, so probably best if you're the one to try it out though
https://bugzilla.yoctoproject.org/show_bug.cgi?id=13868

**Comment by priv-kweihmann** [comment]
As of now nobody can really understand what's going on there, but thanks for letting me know - finally this workaround can go too

**Comment by SJLC** [comment]
Does this one get reopened since upstream didn't fully fix?

**Comment by priv-kweihmann** [comment]
@SJLC I'm in discussion with upstream - as of now I think the ticket doesn't need to be reopened, as upstream is a bit reluctant to fully address the issue - so the classes will be still needed
