### ISSUE TITLE
Revert #9180

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#9225]
**Describe the bug**

> File: '/opt/build/sources/poky/meta/classes/staging.bbclass', lineno: 158, function: staging_copyfile
>      0154:        os.symlink(linkto, dest)
>      0155:        #bb.warn(c)
>      0156:    else:
>      0157:        try:
>  *** 0158:            os.link(c, dest)
>      0159:        except OSError as err:
>      0160:            if err.errno == errno.EXDEV:
>      0161:                bb.utils.copyfile(c, dest)
>      0162:            else:
> Exception: FileNotFoundError: [Errno 2] No such file or directory: '/opt/build/build/tmp/sysroots-components/x86_64/python3-safety-native/usr/lib/python3.10/site-packages/safety/__pycache__/formatter.cpython-310.pyc' -> '/opt/build/build/tmp/work/core2-64-scatest-linux/busybox/1.35.0-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/safety/__pycache__/formatter.cpython-310.pyc'

Sadly upstream only fixed that for a few recipe but not in general

**Comment by SJLC** [comment]
:/
