### ISSUE TITLE
a huge pack file in the git repo

### ISSUE THREAD

**Issue by vermaete** [priv-kweihmann/meta-sca#9273]
There is a rather huge pack file in the .git.
845M    ./.git/objects/pack/pack-8cd55dfdd585b9262636286ed0b5741d6d8fbd4e.pack
On a total of 862M.

Could this be cleaned-up?

**Comment by priv-kweihmann** [comment]
This surely belongs to a long gone commit - and I mentioned it in different forums a bunch of times, that I'm *not* going to rewrite the history of this repo just to remove those - as this will inevitably break existing setups.

BTW this repo is not meant to be clone of a regular (as it's fairly large) - you may want to stick to [meta-sca-minified](https://github.com/priv-kweihmann/meta-sca-minified).

Apart from that I trust GitHub housekeeping enough to be sure that this pack file still holds references to old revisions of some branch in this layer.

**Comment by vermaete** [comment]
Hi,

I do understand you point and I missed the discussion in the past.  Sorry for that.

The meta-sca-minified looks perfect for our CI/CD.
But I'm missing the scripts/results2console script there to create the log files for the artifacts.

Could this be added?

br,

Thanks

**Comment by priv-kweihmann** [comment]
Sure will try to add that in the next release (due date end of this month)
