### ISSUE TITLE
Missing tracefiles?

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#9502]
And I got this error on my local build :

ERROR: gobject-introspection-1.62.0-r0 do_sca_tracefiles: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_sca_tracefiles(d)
     0003:
File: '/home/slucas/meta-sca/repo3/sources/meta-sca/classes/sca-tracefiles.bbclass', lineno: 82, function: do_sca_tracefiles
     0078:
     0079:python do_sca_tracefiles() {
     0080:    import json
     0081:    with open(d.expand("${SCA_TRACEFILES_LIST}"), "w") as o:
 *** 0082:        json.dump(sca_get_trace_files(d), o)
     0083:}
     0084:
     0085:addtask do_sca_tracefiles after do_install before do_package
     0086:
File: '/home/slucas/meta-sca/repo3/sources/meta-sca/classes/sca-tracefiles.bbclass', lineno: 55, function: sca_get_trace_files
     0051:    _res = {}
     0052:    _pkg_files = sca_get_pkg_files(d)
     0053:    for k, v in _pkg_files.items():
     0054:        try:
 *** 0055:            cmd_out = subprocess.check_output(["tracefiles", d.getVar("D"), d.getVar("SCA_SOURCES_DIR")] + v)
     0056:        except subprocess.CalledProcessError as e:
     0057:            cmd_out = e.output or ""
     0058:
     0059:        if not isinstance(cmd_out, str):
File: '/usr/lib/python3.6/subprocess.py', lineno: 356, function: check_output
     0352:        # empty string. That is maintained here for backwards compatibility.
     0353:        kwargs['input'] = '' if kwargs.get('universal_newlines', False) else b''
     0354:
     0355:    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
 *** 0356:               **kwargs).stdout
     0357:
     0358:
     0359:class CompletedProcess(object):
     0360:    """A process that has finished running.
File: '/usr/lib/python3.6/subprocess.py', lineno: 423, function: run
     0419:        if 'stdin' in kwargs:
     0420:            raise ValueError('stdin and input arguments may not both be used.')
     0421:        kwargs['stdin'] = PIPE
     0422:
 *** 0423:    with Popen(*popenargs, **kwargs) as process:
     0424:        try:
     0425:            stdout, stderr = process.communicate(input, timeout=timeout)
     0426:        except TimeoutExpired:
     0427:            process.kill()
File: '/usr/lib/python3.6/subprocess.py', lineno: 729, function: __init__
     0725:                                startupinfo, creationflags, shell,
     0726:                                p2cread, p2cwrite,
     0727:                                c2pread, c2pwrite,
     0728:                                errread, errwrite,
 *** 0729:                                restore_signals, start_new_session)
     0730:        except:
     0731:            # Cleanup if the child failed starting.
     0732:            for f in filter(None, (self.stdin, self.stdout, self.stderr)):
     0733:                try:
File: '/usr/lib/python3.6/subprocess.py', lineno: 1364, function: _execute_child
     1360:                    if errno_num != 0:
     1361:                        err_msg = os.strerror(errno_num)
     1362:                        if errno_num == errno.ENOENT:
     1363:                            err_msg += ': ' + repr(err_filename)
 *** 1364:                    raise child_exception_type(errno_num, err_msg, err_filename)
     1365:                raise child_exception_type(err_msg)
     1366:
     1367:
     1368:        def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'tracefiles': 'tracefiles'

ERROR: Logfile of failure stored in: /home/slucas/meta-sca/repo3/build-imx_imx-distro_security_sota_test_xwayland/tmp/work/cortexa9t2hf-neon-actia-linux-gnueabi/gobject-introspection/1.62.0-r0/temp/log.do_sca_tracefiles.215
ERROR: Task (/home/slucas/meta-sca/repo3/sources/poky/meta/recipes-gnome/gobject-introspection/gobject-introspection_1.62.0.bb:do_sca_tracefiles) failed with exit code '1'

_Originally posted by @gomme600 in https://github.com/priv-kweihmann/meta-sca/issues/9489#issuecomment-1082823328_

**Comment by gomme600** [comment]
I'm still getting this on the latest commit unfortunately on my local build.

**Comment by priv-kweihmann** [comment]
Same recipe? Could you please run `bitbake gobject-introspection -e | grep ^DEPENDS | grep tracefiles` and see if there's any output

**Comment by gomme600** [comment]
Yep on the same recipe. That grep didn't return anything. When running the command without the grep I get [this](https://zerobin.net/?8e7529074ce1a715#G5x/mm93ak+Cim/9a1JIJTCoV7rWAeqHOGD0EMih0Vs=)

**Comment by priv-kweihmann** [comment]
Huch - a bug in poky...
https://git.yoctoproject.org/poky/tree/meta/recipes-gnome/gobject-introspection/gobject-introspection_1.62.0.bb?h=dunfell#n46

that needs to be `DEPENDS_append_class-target` and not `DEPENDS_class-target_append`.
Could you please patch that locally and try once more - sounds like a patch is needed (but not in meta-sca)

**Comment by gomme600** [comment]
Looks like that worked ! Thanks !

**Comment by priv-kweihmann** [comment]
Would you to willing to post a patch to upstream poky for that?

**Comment by gomme600** [comment]
I'm not sure I know how to do that, it seems to be fixed in the master branch but not on dunfell. Is [this](https://wiki.yoctoproject.org/wiki/Poky_Contributions) the process ?

**Comment by priv-kweihmann** [comment]
I guess that is what you looking for https://www.openembedded.org/wiki/How_to_submit_a_patch_to_OpenEmbedded#Backporting_fixes_to_stable_releases

- check out dunfell against the latest dunfell head
- patch the sources
- commit with sign-off
- `git format-patch -M -1 --subject-prefix="dunfell][PATCH" --cc="steve@sakoman.com"`
- await feedback
- be a happy poky contributer :partying_face:

**Comment by priv-kweihmann** [comment]
@gomme600 can we close the issue here?

**Comment by gomme600** [comment]
Yep!
